set_property IOSTANDARD LVCMOS25 [get_ports uart_rxd]
set_property IOSTANDARD LVCMOS25 [get_ports uart_txd]
set_property IOSTANDARD LVCMOS25 [get_ports reset_n]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_scl_io]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_i2c_sda_io]
set_property IOSTANDARD LVCMOS33 [get_ports {hdmi_rst_n_tri_o[0]}]
set_property IOSTANDARD DIFF_SSTL15 [get_ports sys_clk_p]
set_property PACKAGE_PIN AJ26 [get_ports uart_rxd]
set_property PACKAGE_PIN AK26 [get_ports uart_txd]
set_property PACKAGE_PIN AG27 [get_ports reset_n]
set_property PACKAGE_PIN J24 [get_ports hdmi_i2c_scl_io]
set_property PACKAGE_PIN J23 [get_ports hdmi_i2c_sda_io]
set_property PULLUP true [get_ports hdmi_i2c_scl_io]
set_property PULLUP true [get_ports hdmi_i2c_sda_io]
set_property PACKAGE_PIN K25 [get_ports {hdmi_rst_n_tri_o[0]}]
set_property PACKAGE_PIN AE10 [get_ports sys_clk_p]

set_property IOSTANDARD LVCMOS33 [get_ports {qspi_flash_ss_io[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io0_io]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io1_io]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io2_io]
set_property IOSTANDARD LVCMOS33 [get_ports qspi_flash_io3_io]
set_property PACKAGE_PIN U19 [get_ports {qspi_flash_ss_io[0]}]
set_property PACKAGE_PIN P24 [get_ports qspi_flash_io0_io]
set_property PACKAGE_PIN R25 [get_ports qspi_flash_io1_io]
set_property PACKAGE_PIN R20 [get_ports qspi_flash_io2_io]
set_property PACKAGE_PIN R21 [get_ports qspi_flash_io3_io]

