set_property IOSTANDARD LVCMOS25 [get_ports mipi_phy_if_0_clk_lp_n]
set_property IOSTANDARD LVCMOS25 [get_ports mipi_phy_if_0_clk_lp_p]
set_property IOSTANDARD LVCMOS25 [get_ports {mipi_phy_if_0_data_lp_n[*]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mipi_phy_if_0_data_lp_p[*]}]
set_property IOSTANDARD LVDS_25 [get_ports mipi_phy_if_0_clk_hs_p]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_n[*]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_0_data_hs_p[*]}]
set_property PULLDOWN true  [get_ports {mipi_phy_if_0_data_lp_n[*]}]
set_property PULLDOWN true  [get_ports {mipi_phy_if_0_data_lp_p[*]}]

set_property IOSTANDARD LVCMOS25 [get_ports {csi_rstn_tri_o[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports csi_i2c0_sda_io]
set_property IOSTANDARD LVCMOS25 [get_ports csi_i2c0_scl_io]

set_property PACKAGE_PIN AH24 [get_ports mipi_phy_if_0_clk_lp_n]
set_property PACKAGE_PIN AG24 [get_ports mipi_phy_if_0_clk_lp_p]
set_property PACKAGE_PIN AC25 [get_ports  {mipi_phy_if_0_data_lp_n[0]}]
set_property PACKAGE_PIN AB24 [get_ports {mipi_phy_if_0_data_lp_p[0]}]
set_property PACKAGE_PIN AF25 [get_ports  {mipi_phy_if_0_data_lp_n[1]}]
set_property PACKAGE_PIN AE25 [get_ports {mipi_phy_if_0_data_lp_p[1]}]
set_property PACKAGE_PIN AA23 [get_ports  {mipi_phy_if_0_data_lp_n[2]}]
set_property PACKAGE_PIN AA22 [get_ports {mipi_phy_if_0_data_lp_p[2]}]
set_property PACKAGE_PIN AK25 [get_ports  {mipi_phy_if_0_data_lp_n[3]}]
set_property PACKAGE_PIN AJ24 [get_ports {mipi_phy_if_0_data_lp_p[3]}]
set_property PACKAGE_PIN AG23 [get_ports mipi_phy_if_0_clk_hs_n]
set_property PACKAGE_PIN AF22 [get_ports mipi_phy_if_0_clk_hs_p]
set_property PACKAGE_PIN AD24 [get_ports {mipi_phy_if_0_data_hs_n[0]}]
set_property PACKAGE_PIN AC24 [get_ports {mipi_phy_if_0_data_hs_p[0]}]
set_property PACKAGE_PIN AH25 [get_ports {mipi_phy_if_0_data_hs_n[1]}]
set_property PACKAGE_PIN AG25 [get_ports {mipi_phy_if_0_data_hs_p[1]}]
set_property PACKAGE_PIN AB23 [get_ports {mipi_phy_if_0_data_hs_n[2]}]
set_property PACKAGE_PIN AB22 [get_ports {mipi_phy_if_0_data_hs_p[2]}]
set_property PACKAGE_PIN AK24 [get_ports {mipi_phy_if_0_data_hs_n[3]}]
set_property PACKAGE_PIN AK23 [get_ports {mipi_phy_if_0_data_hs_p[3]}]

set_property PACKAGE_PIN Y28 [get_ports  {csi_rstn_tri_o[0]}]
set_property PACKAGE_PIN AC22 [get_ports csi_i2c0_scl_io]
set_property PACKAGE_PIN AD22 [get_ports csi_i2c0_sda_io]


set_property IOSTANDARD LVCMOS25 [get_ports mipi_phy_if_1_clk_lp_n]
set_property IOSTANDARD LVCMOS25 [get_ports mipi_phy_if_1_clk_lp_p]
set_property IOSTANDARD LVCMOS25 [get_ports {mipi_phy_if_1_data_lp_n[*]}]
set_property IOSTANDARD LVCMOS25 [get_ports {mipi_phy_if_1_data_lp_p[*]}]
set_property IOSTANDARD LVDS_25 [get_ports mipi_phy_if_1_clk_hs_p]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_n[*]}]
set_property IOSTANDARD LVDS_25 [get_ports {mipi_phy_if_1_data_hs_p[*]}]
set_property PULLDOWN true  [get_ports {mipi_phy_if_1_data_lp_n[*]}]
set_property PULLDOWN true  [get_ports {mipi_phy_if_1_data_lp_p[*]}]

set_property IOSTANDARD LVCMOS25 [get_ports {csi_rstn_tri_o[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports csi_i2c1_sda_io]
set_property IOSTANDARD LVCMOS25 [get_ports csi_i2c1_scl_io]


set_property PACKAGE_PIN AF28 [get_ports mipi_phy_if_1_clk_lp_n]
set_property PACKAGE_PIN AE28 [get_ports mipi_phy_if_1_clk_lp_p]
set_property PACKAGE_PIN AB30 [get_ports  {mipi_phy_if_1_data_lp_n[0]}]
set_property PACKAGE_PIN AB29 [get_ports {mipi_phy_if_1_data_lp_p[0]}]
set_property PACKAGE_PIN AF30 [get_ports  {mipi_phy_if_1_data_lp_n[1]}]
set_property PACKAGE_PIN AE30 [get_ports {mipi_phy_if_1_data_lp_p[1]}]
set_property PACKAGE_PIN Y29 [get_ports  {mipi_phy_if_1_data_lp_n[2]}]
set_property PACKAGE_PIN W29 [get_ports {mipi_phy_if_1_data_lp_p[2]}]
set_property PACKAGE_PIN AJ29 [get_ports  {mipi_phy_if_1_data_lp_n[3]}]
set_property PACKAGE_PIN AJ28 [get_ports {mipi_phy_if_1_data_lp_p[3]}]
set_property PACKAGE_PIN AC27 [get_ports mipi_phy_if_1_clk_hs_n]
set_property PACKAGE_PIN AB27 [get_ports mipi_phy_if_1_clk_hs_p]
set_property PACKAGE_PIN AE29 [get_ports {mipi_phy_if_1_data_hs_n[0]}]
set_property PACKAGE_PIN AD29 [get_ports {mipi_phy_if_1_data_hs_p[0]}]
set_property PACKAGE_PIN AH30 [get_ports {mipi_phy_if_1_data_hs_n[1]}]
set_property PACKAGE_PIN AG30 [get_ports {mipi_phy_if_1_data_hs_p[1]}]
set_property PACKAGE_PIN AC30 [get_ports {mipi_phy_if_1_data_hs_n[2]}]
set_property PACKAGE_PIN AC29 [get_ports {mipi_phy_if_1_data_hs_p[2]}]
set_property PACKAGE_PIN AK30 [get_ports {mipi_phy_if_1_data_hs_n[3]}]
set_property PACKAGE_PIN AK29 [get_ports {mipi_phy_if_1_data_hs_p[3]}]
set_property PACKAGE_PIN AA28 [get_ports  {csi_rstn_tri_o[1]}]
set_property PACKAGE_PIN W27 [get_ports csi_i2c1_scl_io]
set_property PACKAGE_PIN W28 [get_ports csi_i2c1_sda_io]


set_property IODELAY_GROUP iodelay_grp0 [get_cells design_1_i/camera_system/csi_4lane_raw10_0/inst/csi_rx_4lane_m0/link/gen_idctl.idctrl/gen_v6_7s.delayctrl]
set_property IODELAY_GROUP iodelay_grp0 [get_cells design_1_i/camera_system/csi_4lane_raw10_0/inst/csi_rx_4lane_m0/link/d0phy/gen_7s.indelay]
set_property IODELAY_GROUP iodelay_grp0 [get_cells design_1_i/camera_system/csi_4lane_raw10_0/inst/csi_rx_4lane_m0/link/d1phy/gen_7s.indelay]
set_property IODELAY_GROUP iodelay_grp0 [get_cells design_1_i/camera_system/csi_4lane_raw10_0/inst/csi_rx_4lane_m0/link/d2phy/gen_7s.indelay]
set_property IODELAY_GROUP iodelay_grp0 [get_cells design_1_i/camera_system/csi_4lane_raw10_0/inst/csi_rx_4lane_m0/link/d3phy/gen_7s.indelay]

set_property IODELAY_GROUP iodelay_grp1 [get_cells design_1_i/camera_system/csi_4lane_raw10_1/inst/csi_rx_4lane_m0/link/gen_idctl.idctrl/gen_v6_7s.delayctrl]
set_property IODELAY_GROUP iodelay_grp1 [get_cells design_1_i/camera_system/csi_4lane_raw10_1/inst/csi_rx_4lane_m0/link/d0phy/gen_7s.indelay]
set_property IODELAY_GROUP iodelay_grp1 [get_cells design_1_i/camera_system/csi_4lane_raw10_1/inst/csi_rx_4lane_m0/link/d1phy/gen_7s.indelay]
set_property IODELAY_GROUP iodelay_grp1 [get_cells design_1_i/camera_system/csi_4lane_raw10_1/inst/csi_rx_4lane_m0/link/d2phy/gen_7s.indelay]
set_property IODELAY_GROUP iodelay_grp1 [get_cells design_1_i/camera_system/csi_4lane_raw10_1/inst/csi_rx_4lane_m0/link/d3phy/gen_7s.indelay]