// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="video_awb,hls_ip_2015_4,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=6.380000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=0,HLS_SYN_DSP=5,HLS_SYN_FF=3032,HLS_SYN_LUT=3380}" *)

module video_awb (
        s_axi_CONTROL_BUS_AWVALID,
        s_axi_CONTROL_BUS_AWREADY,
        s_axi_CONTROL_BUS_AWADDR,
        s_axi_CONTROL_BUS_WVALID,
        s_axi_CONTROL_BUS_WREADY,
        s_axi_CONTROL_BUS_WDATA,
        s_axi_CONTROL_BUS_WSTRB,
        s_axi_CONTROL_BUS_ARVALID,
        s_axi_CONTROL_BUS_ARREADY,
        s_axi_CONTROL_BUS_ARADDR,
        s_axi_CONTROL_BUS_RVALID,
        s_axi_CONTROL_BUS_RREADY,
        s_axi_CONTROL_BUS_RDATA,
        s_axi_CONTROL_BUS_RRESP,
        s_axi_CONTROL_BUS_BVALID,
        s_axi_CONTROL_BUS_BREADY,
        s_axi_CONTROL_BUS_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        video_in_TDATA,
        video_in_TKEEP,
        video_in_TSTRB,
        video_in_TUSER,
        video_in_TLAST,
        video_in_TID,
        video_in_TDEST,
        video_out_TDATA,
        video_out_TKEEP,
        video_out_TSTRB,
        video_out_TUSER,
        video_out_TLAST,
        video_out_TID,
        video_out_TDEST,
        video_in_TVALID,
        video_in_TREADY,
        video_out_TVALID,
        video_out_TREADY
);

parameter    C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32;
parameter    ap_const_int64_8 = 8;
parameter    C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_lv24_0 = 24'b000000000000000000000000;
parameter    ap_const_lv3_0 = 3'b000;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_true = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    C_S_AXI_CONTROL_BUS_WSTRB_WIDTH = (C_S_AXI_CONTROL_BUS_DATA_WIDTH / ap_const_int64_8);
parameter    C_S_AXI_WSTRB_WIDTH = (C_S_AXI_DATA_WIDTH / ap_const_int64_8);

input   s_axi_CONTROL_BUS_AWVALID;
output   s_axi_CONTROL_BUS_AWREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1 : 0] s_axi_CONTROL_BUS_AWADDR;
input   s_axi_CONTROL_BUS_WVALID;
output   s_axi_CONTROL_BUS_WREADY;
input  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1 : 0] s_axi_CONTROL_BUS_WDATA;
input  [C_S_AXI_CONTROL_BUS_WSTRB_WIDTH - 1 : 0] s_axi_CONTROL_BUS_WSTRB;
input   s_axi_CONTROL_BUS_ARVALID;
output   s_axi_CONTROL_BUS_ARREADY;
input  [C_S_AXI_CONTROL_BUS_ADDR_WIDTH - 1 : 0] s_axi_CONTROL_BUS_ARADDR;
output   s_axi_CONTROL_BUS_RVALID;
input   s_axi_CONTROL_BUS_RREADY;
output  [C_S_AXI_CONTROL_BUS_DATA_WIDTH - 1 : 0] s_axi_CONTROL_BUS_RDATA;
output  [1:0] s_axi_CONTROL_BUS_RRESP;
output   s_axi_CONTROL_BUS_BVALID;
input   s_axi_CONTROL_BUS_BREADY;
output  [1:0] s_axi_CONTROL_BUS_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
input  [23:0] video_in_TDATA;
input  [2:0] video_in_TKEEP;
input  [2:0] video_in_TSTRB;
input  [0:0] video_in_TUSER;
input  [0:0] video_in_TLAST;
input  [0:0] video_in_TID;
input  [0:0] video_in_TDEST;
output  [23:0] video_out_TDATA;
output  [2:0] video_out_TKEEP;
output  [2:0] video_out_TSTRB;
output  [0:0] video_out_TUSER;
output  [0:0] video_out_TLAST;
output  [0:0] video_out_TID;
output  [0:0] video_out_TDEST;
input   video_in_TVALID;
output   video_in_TREADY;
output   video_out_TVALID;
input   video_out_TREADY;

reg    ap_rst_n_inv;
wire    video_awb_CONTROL_BUS_s_axi_U_ap_dummy_ce;
wire   [31:0] src_rows;
wire   [31:0] src_cols;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
reg    ap_idle;
wire    video_awb_AXIvideo2Mat_U0_ap_start;
wire    video_awb_AXIvideo2Mat_U0_ap_done;
wire    video_awb_AXIvideo2Mat_U0_ap_continue;
wire    video_awb_AXIvideo2Mat_U0_ap_idle;
wire    video_awb_AXIvideo2Mat_U0_ap_ready;
wire   [23:0] video_awb_AXIvideo2Mat_U0_video_in_TDATA;
wire    video_awb_AXIvideo2Mat_U0_video_in_TVALID;
wire    video_awb_AXIvideo2Mat_U0_video_in_TREADY;
wire   [2:0] video_awb_AXIvideo2Mat_U0_video_in_TKEEP;
wire   [2:0] video_awb_AXIvideo2Mat_U0_video_in_TSTRB;
wire   [0:0] video_awb_AXIvideo2Mat_U0_video_in_TUSER;
wire   [0:0] video_awb_AXIvideo2Mat_U0_video_in_TLAST;
wire   [0:0] video_awb_AXIvideo2Mat_U0_video_in_TID;
wire   [0:0] video_awb_AXIvideo2Mat_U0_video_in_TDEST;
wire   [11:0] video_awb_AXIvideo2Mat_U0_img_rows_V;
wire   [11:0] video_awb_AXIvideo2Mat_U0_img_cols_V;
wire   [7:0] video_awb_AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    video_awb_AXIvideo2Mat_U0_img_data_stream_0_V_full_n;
wire    video_awb_AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] video_awb_AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    video_awb_AXIvideo2Mat_U0_img_data_stream_1_V_full_n;
wire    video_awb_AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] video_awb_AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    video_awb_AXIvideo2Mat_U0_img_data_stream_2_V_full_n;
wire    video_awb_AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire    video_awb_awb_U0_ap_start;
wire    video_awb_awb_U0_ap_done;
wire    video_awb_awb_U0_ap_continue;
wire    video_awb_awb_U0_ap_idle;
wire    video_awb_awb_U0_ap_ready;
wire   [11:0] video_awb_awb_U0_src_rows_V;
wire   [11:0] video_awb_awb_U0_src_cols_V;
wire   [7:0] video_awb_awb_U0_src_data_stream_0_V_dout;
wire    video_awb_awb_U0_src_data_stream_0_V_empty_n;
wire    video_awb_awb_U0_src_data_stream_0_V_read;
wire   [7:0] video_awb_awb_U0_src_data_stream_1_V_dout;
wire    video_awb_awb_U0_src_data_stream_1_V_empty_n;
wire    video_awb_awb_U0_src_data_stream_1_V_read;
wire   [7:0] video_awb_awb_U0_src_data_stream_2_V_dout;
wire    video_awb_awb_U0_src_data_stream_2_V_empty_n;
wire    video_awb_awb_U0_src_data_stream_2_V_read;
wire   [7:0] video_awb_awb_U0_dst_data_stream_0_V_din;
wire    video_awb_awb_U0_dst_data_stream_0_V_full_n;
wire    video_awb_awb_U0_dst_data_stream_0_V_write;
wire   [7:0] video_awb_awb_U0_dst_data_stream_1_V_din;
wire    video_awb_awb_U0_dst_data_stream_1_V_full_n;
wire    video_awb_awb_U0_dst_data_stream_1_V_write;
wire   [7:0] video_awb_awb_U0_dst_data_stream_2_V_din;
wire    video_awb_awb_U0_dst_data_stream_2_V_full_n;
wire    video_awb_awb_U0_dst_data_stream_2_V_write;
wire    video_awb_Mat2AXIvideo_U0_ap_start;
wire    video_awb_Mat2AXIvideo_U0_ap_done;
wire    video_awb_Mat2AXIvideo_U0_ap_continue;
wire    video_awb_Mat2AXIvideo_U0_ap_idle;
wire    video_awb_Mat2AXIvideo_U0_ap_ready;
wire   [11:0] video_awb_Mat2AXIvideo_U0_img_rows_V;
wire   [11:0] video_awb_Mat2AXIvideo_U0_img_cols_V;
wire   [7:0] video_awb_Mat2AXIvideo_U0_img_data_stream_0_V_dout;
wire    video_awb_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n;
wire    video_awb_Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire   [7:0] video_awb_Mat2AXIvideo_U0_img_data_stream_1_V_dout;
wire    video_awb_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n;
wire    video_awb_Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire   [7:0] video_awb_Mat2AXIvideo_U0_img_data_stream_2_V_dout;
wire    video_awb_Mat2AXIvideo_U0_img_data_stream_2_V_empty_n;
wire    video_awb_Mat2AXIvideo_U0_img_data_stream_2_V_read;
wire   [23:0] video_awb_Mat2AXIvideo_U0_video_out_TDATA;
wire    video_awb_Mat2AXIvideo_U0_video_out_TVALID;
wire    video_awb_Mat2AXIvideo_U0_video_out_TREADY;
wire   [2:0] video_awb_Mat2AXIvideo_U0_video_out_TKEEP;
wire   [2:0] video_awb_Mat2AXIvideo_U0_video_out_TSTRB;
wire   [0:0] video_awb_Mat2AXIvideo_U0_video_out_TUSER;
wire   [0:0] video_awb_Mat2AXIvideo_U0_video_out_TLAST;
wire   [0:0] video_awb_Mat2AXIvideo_U0_video_out_TID;
wire   [0:0] video_awb_Mat2AXIvideo_U0_video_out_TDEST;
wire    ap_sig_hs_continue;
wire    img_rgb_src_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_rgb_src_data_stream_0_V_din;
wire    img_rgb_src_data_stream_0_V_full_n;
wire    img_rgb_src_data_stream_0_V_write;
wire   [7:0] img_rgb_src_data_stream_0_V_dout;
wire    img_rgb_src_data_stream_0_V_empty_n;
wire    img_rgb_src_data_stream_0_V_read;
wire    img_rgb_src_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_rgb_src_data_stream_1_V_din;
wire    img_rgb_src_data_stream_1_V_full_n;
wire    img_rgb_src_data_stream_1_V_write;
wire   [7:0] img_rgb_src_data_stream_1_V_dout;
wire    img_rgb_src_data_stream_1_V_empty_n;
wire    img_rgb_src_data_stream_1_V_read;
wire    img_rgb_src_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_rgb_src_data_stream_2_V_din;
wire    img_rgb_src_data_stream_2_V_full_n;
wire    img_rgb_src_data_stream_2_V_write;
wire   [7:0] img_rgb_src_data_stream_2_V_dout;
wire    img_rgb_src_data_stream_2_V_empty_n;
wire    img_rgb_src_data_stream_2_V_read;
wire    img_rgb_dst_data_stream_0_V_U_ap_dummy_ce;
wire   [7:0] img_rgb_dst_data_stream_0_V_din;
wire    img_rgb_dst_data_stream_0_V_full_n;
wire    img_rgb_dst_data_stream_0_V_write;
wire   [7:0] img_rgb_dst_data_stream_0_V_dout;
wire    img_rgb_dst_data_stream_0_V_empty_n;
wire    img_rgb_dst_data_stream_0_V_read;
wire    img_rgb_dst_data_stream_1_V_U_ap_dummy_ce;
wire   [7:0] img_rgb_dst_data_stream_1_V_din;
wire    img_rgb_dst_data_stream_1_V_full_n;
wire    img_rgb_dst_data_stream_1_V_write;
wire   [7:0] img_rgb_dst_data_stream_1_V_dout;
wire    img_rgb_dst_data_stream_1_V_empty_n;
wire    img_rgb_dst_data_stream_1_V_read;
wire    img_rgb_dst_data_stream_2_V_U_ap_dummy_ce;
wire   [7:0] img_rgb_dst_data_stream_2_V_din;
wire    img_rgb_dst_data_stream_2_V_full_n;
wire    img_rgb_dst_data_stream_2_V_write;
wire   [7:0] img_rgb_dst_data_stream_2_V_dout;
wire    img_rgb_dst_data_stream_2_V_empty_n;
wire    img_rgb_dst_data_stream_2_V_read;
reg    ap_reg_procdone_video_awb_AXIvideo2Mat_U0 = 1'b0;
reg    ap_sig_hs_done;
reg    ap_reg_procdone_video_awb_awb_U0 = 1'b0;
reg    ap_reg_procdone_video_awb_Mat2AXIvideo_U0 = 1'b0;
reg    ap_CS;
wire    ap_sig_top_allready;


video_awb_CONTROL_BUS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_BUS_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_BUS_DATA_WIDTH ))
video_awb_CONTROL_BUS_s_axi_U(
    .AWVALID( s_axi_CONTROL_BUS_AWVALID ),
    .AWREADY( s_axi_CONTROL_BUS_AWREADY ),
    .AWADDR( s_axi_CONTROL_BUS_AWADDR ),
    .WVALID( s_axi_CONTROL_BUS_WVALID ),
    .WREADY( s_axi_CONTROL_BUS_WREADY ),
    .WDATA( s_axi_CONTROL_BUS_WDATA ),
    .WSTRB( s_axi_CONTROL_BUS_WSTRB ),
    .ARVALID( s_axi_CONTROL_BUS_ARVALID ),
    .ARREADY( s_axi_CONTROL_BUS_ARREADY ),
    .ARADDR( s_axi_CONTROL_BUS_ARADDR ),
    .RVALID( s_axi_CONTROL_BUS_RVALID ),
    .RREADY( s_axi_CONTROL_BUS_RREADY ),
    .RDATA( s_axi_CONTROL_BUS_RDATA ),
    .RRESP( s_axi_CONTROL_BUS_RRESP ),
    .BVALID( s_axi_CONTROL_BUS_BVALID ),
    .BREADY( s_axi_CONTROL_BUS_BREADY ),
    .BRESP( s_axi_CONTROL_BUS_BRESP ),
    .ACLK( ap_clk ),
    .ARESET( ap_rst_n_inv ),
    .ACLK_EN( video_awb_CONTROL_BUS_s_axi_U_ap_dummy_ce ),
    .src_rows( src_rows ),
    .src_cols( src_cols ),
    .ap_start( ap_start ),
    .interrupt( interrupt ),
    .ap_ready( ap_ready ),
    .ap_done( ap_done ),
    .ap_idle( ap_idle )
);

video_awb_AXIvideo2Mat video_awb_AXIvideo2Mat_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( video_awb_AXIvideo2Mat_U0_ap_start ),
    .ap_done( video_awb_AXIvideo2Mat_U0_ap_done ),
    .ap_continue( video_awb_AXIvideo2Mat_U0_ap_continue ),
    .ap_idle( video_awb_AXIvideo2Mat_U0_ap_idle ),
    .ap_ready( video_awb_AXIvideo2Mat_U0_ap_ready ),
    .video_in_TDATA( video_awb_AXIvideo2Mat_U0_video_in_TDATA ),
    .video_in_TVALID( video_awb_AXIvideo2Mat_U0_video_in_TVALID ),
    .video_in_TREADY( video_awb_AXIvideo2Mat_U0_video_in_TREADY ),
    .video_in_TKEEP( video_awb_AXIvideo2Mat_U0_video_in_TKEEP ),
    .video_in_TSTRB( video_awb_AXIvideo2Mat_U0_video_in_TSTRB ),
    .video_in_TUSER( video_awb_AXIvideo2Mat_U0_video_in_TUSER ),
    .video_in_TLAST( video_awb_AXIvideo2Mat_U0_video_in_TLAST ),
    .video_in_TID( video_awb_AXIvideo2Mat_U0_video_in_TID ),
    .video_in_TDEST( video_awb_AXIvideo2Mat_U0_video_in_TDEST ),
    .img_rows_V( video_awb_AXIvideo2Mat_U0_img_rows_V ),
    .img_cols_V( video_awb_AXIvideo2Mat_U0_img_cols_V ),
    .img_data_stream_0_V_din( video_awb_AXIvideo2Mat_U0_img_data_stream_0_V_din ),
    .img_data_stream_0_V_full_n( video_awb_AXIvideo2Mat_U0_img_data_stream_0_V_full_n ),
    .img_data_stream_0_V_write( video_awb_AXIvideo2Mat_U0_img_data_stream_0_V_write ),
    .img_data_stream_1_V_din( video_awb_AXIvideo2Mat_U0_img_data_stream_1_V_din ),
    .img_data_stream_1_V_full_n( video_awb_AXIvideo2Mat_U0_img_data_stream_1_V_full_n ),
    .img_data_stream_1_V_write( video_awb_AXIvideo2Mat_U0_img_data_stream_1_V_write ),
    .img_data_stream_2_V_din( video_awb_AXIvideo2Mat_U0_img_data_stream_2_V_din ),
    .img_data_stream_2_V_full_n( video_awb_AXIvideo2Mat_U0_img_data_stream_2_V_full_n ),
    .img_data_stream_2_V_write( video_awb_AXIvideo2Mat_U0_img_data_stream_2_V_write )
);

video_awb_awb video_awb_awb_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( video_awb_awb_U0_ap_start ),
    .ap_done( video_awb_awb_U0_ap_done ),
    .ap_continue( video_awb_awb_U0_ap_continue ),
    .ap_idle( video_awb_awb_U0_ap_idle ),
    .ap_ready( video_awb_awb_U0_ap_ready ),
    .src_rows_V( video_awb_awb_U0_src_rows_V ),
    .src_cols_V( video_awb_awb_U0_src_cols_V ),
    .src_data_stream_0_V_dout( video_awb_awb_U0_src_data_stream_0_V_dout ),
    .src_data_stream_0_V_empty_n( video_awb_awb_U0_src_data_stream_0_V_empty_n ),
    .src_data_stream_0_V_read( video_awb_awb_U0_src_data_stream_0_V_read ),
    .src_data_stream_1_V_dout( video_awb_awb_U0_src_data_stream_1_V_dout ),
    .src_data_stream_1_V_empty_n( video_awb_awb_U0_src_data_stream_1_V_empty_n ),
    .src_data_stream_1_V_read( video_awb_awb_U0_src_data_stream_1_V_read ),
    .src_data_stream_2_V_dout( video_awb_awb_U0_src_data_stream_2_V_dout ),
    .src_data_stream_2_V_empty_n( video_awb_awb_U0_src_data_stream_2_V_empty_n ),
    .src_data_stream_2_V_read( video_awb_awb_U0_src_data_stream_2_V_read ),
    .dst_data_stream_0_V_din( video_awb_awb_U0_dst_data_stream_0_V_din ),
    .dst_data_stream_0_V_full_n( video_awb_awb_U0_dst_data_stream_0_V_full_n ),
    .dst_data_stream_0_V_write( video_awb_awb_U0_dst_data_stream_0_V_write ),
    .dst_data_stream_1_V_din( video_awb_awb_U0_dst_data_stream_1_V_din ),
    .dst_data_stream_1_V_full_n( video_awb_awb_U0_dst_data_stream_1_V_full_n ),
    .dst_data_stream_1_V_write( video_awb_awb_U0_dst_data_stream_1_V_write ),
    .dst_data_stream_2_V_din( video_awb_awb_U0_dst_data_stream_2_V_din ),
    .dst_data_stream_2_V_full_n( video_awb_awb_U0_dst_data_stream_2_V_full_n ),
    .dst_data_stream_2_V_write( video_awb_awb_U0_dst_data_stream_2_V_write )
);

video_awb_Mat2AXIvideo video_awb_Mat2AXIvideo_U0(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst_n_inv ),
    .ap_start( video_awb_Mat2AXIvideo_U0_ap_start ),
    .ap_done( video_awb_Mat2AXIvideo_U0_ap_done ),
    .ap_continue( video_awb_Mat2AXIvideo_U0_ap_continue ),
    .ap_idle( video_awb_Mat2AXIvideo_U0_ap_idle ),
    .ap_ready( video_awb_Mat2AXIvideo_U0_ap_ready ),
    .img_rows_V( video_awb_Mat2AXIvideo_U0_img_rows_V ),
    .img_cols_V( video_awb_Mat2AXIvideo_U0_img_cols_V ),
    .img_data_stream_0_V_dout( video_awb_Mat2AXIvideo_U0_img_data_stream_0_V_dout ),
    .img_data_stream_0_V_empty_n( video_awb_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n ),
    .img_data_stream_0_V_read( video_awb_Mat2AXIvideo_U0_img_data_stream_0_V_read ),
    .img_data_stream_1_V_dout( video_awb_Mat2AXIvideo_U0_img_data_stream_1_V_dout ),
    .img_data_stream_1_V_empty_n( video_awb_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n ),
    .img_data_stream_1_V_read( video_awb_Mat2AXIvideo_U0_img_data_stream_1_V_read ),
    .img_data_stream_2_V_dout( video_awb_Mat2AXIvideo_U0_img_data_stream_2_V_dout ),
    .img_data_stream_2_V_empty_n( video_awb_Mat2AXIvideo_U0_img_data_stream_2_V_empty_n ),
    .img_data_stream_2_V_read( video_awb_Mat2AXIvideo_U0_img_data_stream_2_V_read ),
    .video_out_TDATA( video_awb_Mat2AXIvideo_U0_video_out_TDATA ),
    .video_out_TVALID( video_awb_Mat2AXIvideo_U0_video_out_TVALID ),
    .video_out_TREADY( video_awb_Mat2AXIvideo_U0_video_out_TREADY ),
    .video_out_TKEEP( video_awb_Mat2AXIvideo_U0_video_out_TKEEP ),
    .video_out_TSTRB( video_awb_Mat2AXIvideo_U0_video_out_TSTRB ),
    .video_out_TUSER( video_awb_Mat2AXIvideo_U0_video_out_TUSER ),
    .video_out_TLAST( video_awb_Mat2AXIvideo_U0_video_out_TLAST ),
    .video_out_TID( video_awb_Mat2AXIvideo_U0_video_out_TID ),
    .video_out_TDEST( video_awb_Mat2AXIvideo_U0_video_out_TDEST )
);

FIFO_video_awb_img_rgb_src_data_stream_0_V img_rgb_src_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_rgb_src_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_rgb_src_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_rgb_src_data_stream_0_V_din ),
    .if_full_n( img_rgb_src_data_stream_0_V_full_n ),
    .if_write( img_rgb_src_data_stream_0_V_write ),
    .if_dout( img_rgb_src_data_stream_0_V_dout ),
    .if_empty_n( img_rgb_src_data_stream_0_V_empty_n ),
    .if_read( img_rgb_src_data_stream_0_V_read )
);

FIFO_video_awb_img_rgb_src_data_stream_1_V img_rgb_src_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_rgb_src_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_rgb_src_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_rgb_src_data_stream_1_V_din ),
    .if_full_n( img_rgb_src_data_stream_1_V_full_n ),
    .if_write( img_rgb_src_data_stream_1_V_write ),
    .if_dout( img_rgb_src_data_stream_1_V_dout ),
    .if_empty_n( img_rgb_src_data_stream_1_V_empty_n ),
    .if_read( img_rgb_src_data_stream_1_V_read )
);

FIFO_video_awb_img_rgb_src_data_stream_2_V img_rgb_src_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_rgb_src_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_rgb_src_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_rgb_src_data_stream_2_V_din ),
    .if_full_n( img_rgb_src_data_stream_2_V_full_n ),
    .if_write( img_rgb_src_data_stream_2_V_write ),
    .if_dout( img_rgb_src_data_stream_2_V_dout ),
    .if_empty_n( img_rgb_src_data_stream_2_V_empty_n ),
    .if_read( img_rgb_src_data_stream_2_V_read )
);

FIFO_video_awb_img_rgb_dst_data_stream_0_V img_rgb_dst_data_stream_0_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_rgb_dst_data_stream_0_V_U_ap_dummy_ce ),
    .if_write_ce( img_rgb_dst_data_stream_0_V_U_ap_dummy_ce ),
    .if_din( img_rgb_dst_data_stream_0_V_din ),
    .if_full_n( img_rgb_dst_data_stream_0_V_full_n ),
    .if_write( img_rgb_dst_data_stream_0_V_write ),
    .if_dout( img_rgb_dst_data_stream_0_V_dout ),
    .if_empty_n( img_rgb_dst_data_stream_0_V_empty_n ),
    .if_read( img_rgb_dst_data_stream_0_V_read )
);

FIFO_video_awb_img_rgb_dst_data_stream_1_V img_rgb_dst_data_stream_1_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_rgb_dst_data_stream_1_V_U_ap_dummy_ce ),
    .if_write_ce( img_rgb_dst_data_stream_1_V_U_ap_dummy_ce ),
    .if_din( img_rgb_dst_data_stream_1_V_din ),
    .if_full_n( img_rgb_dst_data_stream_1_V_full_n ),
    .if_write( img_rgb_dst_data_stream_1_V_write ),
    .if_dout( img_rgb_dst_data_stream_1_V_dout ),
    .if_empty_n( img_rgb_dst_data_stream_1_V_empty_n ),
    .if_read( img_rgb_dst_data_stream_1_V_read )
);

FIFO_video_awb_img_rgb_dst_data_stream_2_V img_rgb_dst_data_stream_2_V_U(
    .clk( ap_clk ),
    .reset( ap_rst_n_inv ),
    .if_read_ce( img_rgb_dst_data_stream_2_V_U_ap_dummy_ce ),
    .if_write_ce( img_rgb_dst_data_stream_2_V_U_ap_dummy_ce ),
    .if_din( img_rgb_dst_data_stream_2_V_din ),
    .if_full_n( img_rgb_dst_data_stream_2_V_full_n ),
    .if_write( img_rgb_dst_data_stream_2_V_write ),
    .if_dout( img_rgb_dst_data_stream_2_V_dout ),
    .if_empty_n( img_rgb_dst_data_stream_2_V_empty_n ),
    .if_read( img_rgb_dst_data_stream_2_V_read )
);



always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_video_awb_AXIvideo2Mat_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_video_awb_AXIvideo2Mat_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_video_awb_AXIvideo2Mat_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == video_awb_AXIvideo2Mat_U0_ap_done)) begin
            ap_reg_procdone_video_awb_AXIvideo2Mat_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_video_awb_Mat2AXIvideo_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_video_awb_Mat2AXIvideo_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_video_awb_Mat2AXIvideo_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == video_awb_Mat2AXIvideo_U0_ap_done)) begin
            ap_reg_procdone_video_awb_Mat2AXIvideo_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_procdone_video_awb_awb_U0
    if (ap_rst_n_inv == 1'b1) begin
        ap_reg_procdone_video_awb_awb_U0 <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_sig_hs_done)) begin
            ap_reg_procdone_video_awb_awb_U0 <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == video_awb_awb_U0_ap_done)) begin
            ap_reg_procdone_video_awb_awb_U0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin
    ap_CS <= ap_const_logic_0;
end

always @ (video_awb_AXIvideo2Mat_U0_ap_idle or video_awb_awb_U0_ap_idle or video_awb_Mat2AXIvideo_U0_ap_idle) begin
    if (((ap_const_logic_1 == video_awb_AXIvideo2Mat_U0_ap_idle) & (ap_const_logic_1 == video_awb_awb_U0_ap_idle) & (ap_const_logic_1 == video_awb_Mat2AXIvideo_U0_ap_idle))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (video_awb_Mat2AXIvideo_U0_ap_done) begin
    if ((ap_const_logic_1 == video_awb_Mat2AXIvideo_U0_ap_done)) begin
        ap_sig_hs_done = ap_const_logic_1;
    end else begin
        ap_sig_hs_done = ap_const_logic_0;
    end
end

assign ap_done = ap_sig_hs_done;

assign ap_ready = ap_sig_top_allready;


always @ (ap_rst_n) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sig_hs_continue = ap_const_logic_1;

assign ap_sig_top_allready = video_awb_AXIvideo2Mat_U0_ap_ready;

assign img_rgb_dst_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_rgb_dst_data_stream_0_V_din = video_awb_awb_U0_dst_data_stream_0_V_din;

assign img_rgb_dst_data_stream_0_V_read = video_awb_Mat2AXIvideo_U0_img_data_stream_0_V_read;

assign img_rgb_dst_data_stream_0_V_write = video_awb_awb_U0_dst_data_stream_0_V_write;

assign img_rgb_dst_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_rgb_dst_data_stream_1_V_din = video_awb_awb_U0_dst_data_stream_1_V_din;

assign img_rgb_dst_data_stream_1_V_read = video_awb_Mat2AXIvideo_U0_img_data_stream_1_V_read;

assign img_rgb_dst_data_stream_1_V_write = video_awb_awb_U0_dst_data_stream_1_V_write;

assign img_rgb_dst_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_rgb_dst_data_stream_2_V_din = video_awb_awb_U0_dst_data_stream_2_V_din;

assign img_rgb_dst_data_stream_2_V_read = video_awb_Mat2AXIvideo_U0_img_data_stream_2_V_read;

assign img_rgb_dst_data_stream_2_V_write = video_awb_awb_U0_dst_data_stream_2_V_write;

assign img_rgb_src_data_stream_0_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_rgb_src_data_stream_0_V_din = video_awb_AXIvideo2Mat_U0_img_data_stream_0_V_din;

assign img_rgb_src_data_stream_0_V_read = video_awb_awb_U0_src_data_stream_0_V_read;

assign img_rgb_src_data_stream_0_V_write = video_awb_AXIvideo2Mat_U0_img_data_stream_0_V_write;

assign img_rgb_src_data_stream_1_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_rgb_src_data_stream_1_V_din = video_awb_AXIvideo2Mat_U0_img_data_stream_1_V_din;

assign img_rgb_src_data_stream_1_V_read = video_awb_awb_U0_src_data_stream_1_V_read;

assign img_rgb_src_data_stream_1_V_write = video_awb_AXIvideo2Mat_U0_img_data_stream_1_V_write;

assign img_rgb_src_data_stream_2_V_U_ap_dummy_ce = ap_const_logic_1;

assign img_rgb_src_data_stream_2_V_din = video_awb_AXIvideo2Mat_U0_img_data_stream_2_V_din;

assign img_rgb_src_data_stream_2_V_read = video_awb_awb_U0_src_data_stream_2_V_read;

assign img_rgb_src_data_stream_2_V_write = video_awb_AXIvideo2Mat_U0_img_data_stream_2_V_write;

assign video_awb_AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;

assign video_awb_AXIvideo2Mat_U0_ap_start = ap_start;

assign video_awb_AXIvideo2Mat_U0_img_cols_V = {{src_cols[(ap_const_lv32_C - 32'd1) : ap_const_lv32_0]}};

assign video_awb_AXIvideo2Mat_U0_img_data_stream_0_V_full_n = img_rgb_src_data_stream_0_V_full_n;

assign video_awb_AXIvideo2Mat_U0_img_data_stream_1_V_full_n = img_rgb_src_data_stream_1_V_full_n;

assign video_awb_AXIvideo2Mat_U0_img_data_stream_2_V_full_n = img_rgb_src_data_stream_2_V_full_n;

assign video_awb_AXIvideo2Mat_U0_img_rows_V = {{src_rows[(ap_const_lv32_C - 32'd1) : ap_const_lv32_0]}};

assign video_awb_AXIvideo2Mat_U0_video_in_TDATA = video_in_TDATA;

assign video_awb_AXIvideo2Mat_U0_video_in_TDEST = video_in_TDEST;

assign video_awb_AXIvideo2Mat_U0_video_in_TID = video_in_TID;

assign video_awb_AXIvideo2Mat_U0_video_in_TKEEP = video_in_TKEEP;

assign video_awb_AXIvideo2Mat_U0_video_in_TLAST = video_in_TLAST;

assign video_awb_AXIvideo2Mat_U0_video_in_TSTRB = video_in_TSTRB;

assign video_awb_AXIvideo2Mat_U0_video_in_TUSER = video_in_TUSER;

assign video_awb_AXIvideo2Mat_U0_video_in_TVALID = video_in_TVALID;

assign video_awb_CONTROL_BUS_s_axi_U_ap_dummy_ce = ap_const_logic_1;

assign video_awb_Mat2AXIvideo_U0_ap_continue = ap_sig_hs_continue;

assign video_awb_Mat2AXIvideo_U0_ap_start = ap_start;

assign video_awb_Mat2AXIvideo_U0_img_cols_V = {{src_cols[(ap_const_lv32_C - 32'd1) : ap_const_lv32_0]}};

assign video_awb_Mat2AXIvideo_U0_img_data_stream_0_V_dout = img_rgb_dst_data_stream_0_V_dout;

assign video_awb_Mat2AXIvideo_U0_img_data_stream_0_V_empty_n = img_rgb_dst_data_stream_0_V_empty_n;

assign video_awb_Mat2AXIvideo_U0_img_data_stream_1_V_dout = img_rgb_dst_data_stream_1_V_dout;

assign video_awb_Mat2AXIvideo_U0_img_data_stream_1_V_empty_n = img_rgb_dst_data_stream_1_V_empty_n;

assign video_awb_Mat2AXIvideo_U0_img_data_stream_2_V_dout = img_rgb_dst_data_stream_2_V_dout;

assign video_awb_Mat2AXIvideo_U0_img_data_stream_2_V_empty_n = img_rgb_dst_data_stream_2_V_empty_n;

assign video_awb_Mat2AXIvideo_U0_img_rows_V = {{src_rows[(ap_const_lv32_C - 32'd1) : ap_const_lv32_0]}};

assign video_awb_Mat2AXIvideo_U0_video_out_TREADY = video_out_TREADY;

assign video_awb_awb_U0_ap_continue = ap_const_logic_1;

assign video_awb_awb_U0_ap_start = ap_start;

assign video_awb_awb_U0_dst_data_stream_0_V_full_n = img_rgb_dst_data_stream_0_V_full_n;

assign video_awb_awb_U0_dst_data_stream_1_V_full_n = img_rgb_dst_data_stream_1_V_full_n;

assign video_awb_awb_U0_dst_data_stream_2_V_full_n = img_rgb_dst_data_stream_2_V_full_n;

assign video_awb_awb_U0_src_cols_V = {{src_cols[(ap_const_lv32_C - 32'd1) : ap_const_lv32_0]}};

assign video_awb_awb_U0_src_data_stream_0_V_dout = img_rgb_src_data_stream_0_V_dout;

assign video_awb_awb_U0_src_data_stream_0_V_empty_n = img_rgb_src_data_stream_0_V_empty_n;

assign video_awb_awb_U0_src_data_stream_1_V_dout = img_rgb_src_data_stream_1_V_dout;

assign video_awb_awb_U0_src_data_stream_1_V_empty_n = img_rgb_src_data_stream_1_V_empty_n;

assign video_awb_awb_U0_src_data_stream_2_V_dout = img_rgb_src_data_stream_2_V_dout;

assign video_awb_awb_U0_src_data_stream_2_V_empty_n = img_rgb_src_data_stream_2_V_empty_n;

assign video_awb_awb_U0_src_rows_V = {{src_rows[(ap_const_lv32_C - 32'd1) : ap_const_lv32_0]}};

assign video_in_TREADY = video_awb_AXIvideo2Mat_U0_video_in_TREADY;

assign video_out_TDATA = video_awb_Mat2AXIvideo_U0_video_out_TDATA;

assign video_out_TDEST = video_awb_Mat2AXIvideo_U0_video_out_TDEST;

assign video_out_TID = video_awb_Mat2AXIvideo_U0_video_out_TID;

assign video_out_TKEEP = video_awb_Mat2AXIvideo_U0_video_out_TKEEP;

assign video_out_TLAST = video_awb_Mat2AXIvideo_U0_video_out_TLAST;

assign video_out_TSTRB = video_awb_Mat2AXIvideo_U0_video_out_TSTRB;

assign video_out_TUSER = video_awb_Mat2AXIvideo_U0_video_out_TUSER;

assign video_out_TVALID = video_awb_Mat2AXIvideo_U0_video_out_TVALID;


endmodule //video_awb

