// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module video_awb_awb (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        src_rows_V,
        src_cols_V,
        src_data_stream_0_V_dout,
        src_data_stream_0_V_empty_n,
        src_data_stream_0_V_read,
        src_data_stream_1_V_dout,
        src_data_stream_1_V_empty_n,
        src_data_stream_1_V_read,
        src_data_stream_2_V_dout,
        src_data_stream_2_V_empty_n,
        src_data_stream_2_V_read,
        dst_data_stream_0_V_din,
        dst_data_stream_0_V_full_n,
        dst_data_stream_0_V_write,
        dst_data_stream_1_V_din,
        dst_data_stream_1_V_full_n,
        dst_data_stream_1_V_write,
        dst_data_stream_2_V_din,
        dst_data_stream_2_V_full_n,
        dst_data_stream_2_V_write
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 42'b1;
parameter    ap_ST_st2_fsm_1 = 42'b10;
parameter    ap_ST_pp0_stg0_fsm_2 = 42'b100;
parameter    ap_ST_st29_fsm_3 = 42'b1000;
parameter    ap_ST_st30_fsm_4 = 42'b10000;
parameter    ap_ST_st31_fsm_5 = 42'b100000;
parameter    ap_ST_st32_fsm_6 = 42'b1000000;
parameter    ap_ST_st33_fsm_7 = 42'b10000000;
parameter    ap_ST_st34_fsm_8 = 42'b100000000;
parameter    ap_ST_st35_fsm_9 = 42'b1000000000;
parameter    ap_ST_st36_fsm_10 = 42'b10000000000;
parameter    ap_ST_st37_fsm_11 = 42'b100000000000;
parameter    ap_ST_st38_fsm_12 = 42'b1000000000000;
parameter    ap_ST_st39_fsm_13 = 42'b10000000000000;
parameter    ap_ST_st40_fsm_14 = 42'b100000000000000;
parameter    ap_ST_st41_fsm_15 = 42'b1000000000000000;
parameter    ap_ST_st42_fsm_16 = 42'b10000000000000000;
parameter    ap_ST_st43_fsm_17 = 42'b100000000000000000;
parameter    ap_ST_st44_fsm_18 = 42'b1000000000000000000;
parameter    ap_ST_st45_fsm_19 = 42'b10000000000000000000;
parameter    ap_ST_st46_fsm_20 = 42'b100000000000000000000;
parameter    ap_ST_st47_fsm_21 = 42'b1000000000000000000000;
parameter    ap_ST_st48_fsm_22 = 42'b10000000000000000000000;
parameter    ap_ST_st49_fsm_23 = 42'b100000000000000000000000;
parameter    ap_ST_st50_fsm_24 = 42'b1000000000000000000000000;
parameter    ap_ST_st51_fsm_25 = 42'b10000000000000000000000000;
parameter    ap_ST_st52_fsm_26 = 42'b100000000000000000000000000;
parameter    ap_ST_st53_fsm_27 = 42'b1000000000000000000000000000;
parameter    ap_ST_st54_fsm_28 = 42'b10000000000000000000000000000;
parameter    ap_ST_st55_fsm_29 = 42'b100000000000000000000000000000;
parameter    ap_ST_st56_fsm_30 = 42'b1000000000000000000000000000000;
parameter    ap_ST_st57_fsm_31 = 42'b10000000000000000000000000000000;
parameter    ap_ST_st58_fsm_32 = 42'b100000000000000000000000000000000;
parameter    ap_ST_st59_fsm_33 = 42'b1000000000000000000000000000000000;
parameter    ap_ST_st60_fsm_34 = 42'b10000000000000000000000000000000000;
parameter    ap_ST_st61_fsm_35 = 42'b100000000000000000000000000000000000;
parameter    ap_ST_st62_fsm_36 = 42'b1000000000000000000000000000000000000;
parameter    ap_ST_st63_fsm_37 = 42'b10000000000000000000000000000000000000;
parameter    ap_ST_st64_fsm_38 = 42'b100000000000000000000000000000000000000;
parameter    ap_ST_st65_fsm_39 = 42'b1000000000000000000000000000000000000000;
parameter    ap_ST_st66_fsm_40 = 42'b10000000000000000000000000000000000000000;
parameter    ap_ST_st67_fsm_41 = 42'b100000000000000000000000000000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv8_0 = 8'b00000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv32_26 = 32'b100110;
parameter    ap_const_lv32_27 = 32'b100111;
parameter    ap_const_lv32_28 = 32'b101000;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_29 = 32'b101001;
parameter    ap_const_lv12_1 = 12'b1;
parameter    ap_const_lv8_FF = 8'b11111111;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_15 = 32'b10101;
parameter    ap_const_lv22_556 = 22'b10101010110;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [11:0] src_rows_V;
input  [11:0] src_cols_V;
input  [7:0] src_data_stream_0_V_dout;
input   src_data_stream_0_V_empty_n;
output   src_data_stream_0_V_read;
input  [7:0] src_data_stream_1_V_dout;
input   src_data_stream_1_V_empty_n;
output   src_data_stream_1_V_read;
input  [7:0] src_data_stream_2_V_dout;
input   src_data_stream_2_V_empty_n;
output   src_data_stream_2_V_read;
output  [7:0] dst_data_stream_0_V_din;
input   dst_data_stream_0_V_full_n;
output   dst_data_stream_0_V_write;
output  [7:0] dst_data_stream_1_V_din;
input   dst_data_stream_1_V_full_n;
output   dst_data_stream_1_V_write;
output  [7:0] dst_data_stream_2_V_din;
input   dst_data_stream_2_V_full_n;
output   dst_data_stream_2_V_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg src_data_stream_0_V_read;
reg src_data_stream_1_V_read;
reg src_data_stream_2_V_read;
reg dst_data_stream_0_V_write;
reg dst_data_stream_1_V_write;
reg dst_data_stream_2_V_write;
reg    ap_done_reg = 1'b0;
(* fsm_encoding = "none" *) reg   [41:0] ap_CS_fsm = 42'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_61;
reg   [9:0] K = 10'b0000000000;
reg   [7:0] aver_r = 8'b00000000;
reg   [7:0] aver_g = 8'b00000000;
reg   [7:0] aver_b = 8'b00000000;
reg   [11:0] col_i_reg_162;
reg    ap_sig_bdd_107;
wire   [31:0] tatol_pixs_cast_i_fu_190_p1;
wire   [0:0] exitcond4_i_fu_208_p2;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_121;
wire   [11:0] row_fu_213_p2;
reg   [11:0] row_reg_603;
wire   [0:0] exitcond_i_fu_234_p2;
reg   [0:0] exitcond_i_reg_623;
reg    ap_sig_cseq_ST_pp0_stg0_fsm_2;
reg    ap_sig_bdd_142;
reg    ap_reg_ppiten_pp0_it0 = 1'b0;
reg    ap_sig_bdd_155;
reg    ap_reg_ppiten_pp0_it1 = 1'b0;
reg    ap_reg_ppiten_pp0_it2 = 1'b0;
reg    ap_reg_ppiten_pp0_it3 = 1'b0;
reg    ap_reg_ppiten_pp0_it4 = 1'b0;
reg    ap_reg_ppiten_pp0_it5 = 1'b0;
reg    ap_reg_ppiten_pp0_it6 = 1'b0;
reg    ap_reg_ppiten_pp0_it7 = 1'b0;
reg    ap_reg_ppiten_pp0_it8 = 1'b0;
reg    ap_reg_ppiten_pp0_it9 = 1'b0;
reg    ap_reg_ppiten_pp0_it10 = 1'b0;
reg    ap_reg_ppiten_pp0_it11 = 1'b0;
reg    ap_reg_ppiten_pp0_it12 = 1'b0;
reg    ap_reg_ppiten_pp0_it13 = 1'b0;
reg    ap_reg_ppiten_pp0_it14 = 1'b0;
reg    ap_reg_ppiten_pp0_it15 = 1'b0;
reg    ap_reg_ppiten_pp0_it16 = 1'b0;
reg    ap_reg_ppiten_pp0_it17 = 1'b0;
reg    ap_reg_ppiten_pp0_it18 = 1'b0;
reg    ap_reg_ppiten_pp0_it19 = 1'b0;
reg    ap_reg_ppiten_pp0_it20 = 1'b0;
reg    ap_reg_ppiten_pp0_it21 = 1'b0;
reg    ap_reg_ppiten_pp0_it22 = 1'b0;
reg    ap_reg_ppiten_pp0_it23 = 1'b0;
reg    ap_reg_ppiten_pp0_it24 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it24;
reg    ap_sig_bdd_215;
reg    ap_reg_ppiten_pp0_it25 = 1'b0;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it1;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it2;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it3;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it4;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it5;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it6;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it7;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it8;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it9;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it10;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it11;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it12;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it13;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it14;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it15;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it16;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it17;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it18;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it19;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it20;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it21;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it22;
reg   [0:0] ap_reg_ppstg_exitcond_i_reg_623_pp0_it23;
wire   [11:0] col_fu_239_p2;
reg   [7:0] tmp_25_reg_632;
reg   [7:0] tmp_26_reg_638;
reg   [7:0] tmp_9_reg_644;
wire   [15:0] grp_fu_283_p2;
reg   [15:0] tmp_12_reg_680;
wire   [15:0] grp_fu_296_p2;
reg   [15:0] tmp_15_reg_686;
wire   [15:0] grp_fu_309_p2;
reg   [15:0] tmp_18_reg_692;
wire   [0:0] ult_fu_384_p2;
reg   [0:0] ult_reg_713;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it6;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it7;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it8;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it9;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it10;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it11;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it12;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it13;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it14;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it15;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it16;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it17;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it18;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it19;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it20;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it21;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it22;
reg   [0:0] ap_reg_ppstg_ult_reg_713_pp0_it23;
wire   [0:0] ult1_fu_405_p2;
reg   [0:0] ult1_reg_718;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it6;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it7;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it8;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it9;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it10;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it11;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it12;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it13;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it14;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it15;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it16;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it17;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it18;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it19;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it20;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it21;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it22;
reg   [0:0] ap_reg_ppstg_ult1_reg_718_pp0_it23;
wire   [0:0] ult2_fu_426_p2;
reg   [0:0] ult2_reg_723;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it6;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it7;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it8;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it9;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it10;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it11;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it12;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it13;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it14;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it15;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it16;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it17;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it18;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it19;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it20;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it21;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it22;
reg   [0:0] ap_reg_ppstg_ult2_reg_723_pp0_it23;
wire   [7:0] tmp_7_fu_441_p3;
reg   [7:0] tmp_7_reg_728;
wire   [7:0] tmp_6_fu_458_p3;
reg   [7:0] tmp_6_reg_733;
wire   [7:0] tmp_5_fu_475_p3;
reg   [7:0] tmp_5_reg_738;
wire   [7:0] tmp_fu_483_p1;
reg   [7:0] tmp_reg_743;
reg    ap_sig_cseq_ST_st64_fsm_38;
reg    ap_sig_bdd_494;
wire    grp_fu_219_ap_done;
wire    grp_fu_224_ap_done;
wire    grp_fu_229_ap_done;
wire   [7:0] tmp_2_fu_493_p1;
reg   [7:0] tmp_2_reg_748;
wire   [7:0] tmp_3_fu_503_p1;
reg   [7:0] tmp_3_reg_753;
wire   [8:0] tmp_10_i_fu_519_p2;
reg   [8:0] tmp_10_i_reg_758;
reg    ap_sig_cseq_ST_st65_fsm_39;
reg    ap_sig_bdd_517;
wire   [21:0] grp_fu_553_p3;
reg   [21:0] mul_reg_763;
reg    ap_sig_cseq_ST_st66_fsm_40;
reg    ap_sig_bdd_526;
reg   [11:0] row_i_reg_151;
reg    ap_sig_cseq_ST_st29_fsm_3;
reg    ap_sig_bdd_542;
reg    ap_sig_cseq_ST_st67_fsm_41;
reg    ap_sig_bdd_563;
reg   [31:0] sum_b_1_fu_88;
wire   [31:0] sum_b_fu_266_p2;
reg   [31:0] sum_g_1_fu_92;
wire   [31:0] sum_g_fu_257_p2;
reg   [31:0] sum_r_1_fu_96;
wire   [31:0] sum_r_fu_248_p2;
wire   [23:0] tatol_pixs_fu_546_p2;
wire   [23:0] grp_fu_219_p1;
wire   [23:0] grp_fu_224_p1;
wire   [23:0] grp_fu_229_p1;
wire   [31:0] tmp_14_i_fu_245_p1;
wire   [31:0] tmp_15_i_fu_254_p1;
wire   [31:0] tmp_16_i_fu_263_p1;
wire   [7:0] grp_fu_283_p0;
wire   [9:0] grp_fu_283_p1;
wire   [7:0] grp_fu_296_p0;
wire   [9:0] grp_fu_296_p1;
wire   [7:0] grp_fu_309_p0;
wire   [9:0] grp_fu_309_p1;
wire   [7:0] grp_fu_338_p1;
wire   [7:0] grp_fu_351_p1;
wire   [7:0] grp_fu_364_p1;
wire   [15:0] tmp_19_fu_369_p3;
wire   [24:0] x_fu_381_p1;
wire   [24:0] p2y_fu_377_p1;
wire   [15:0] tmp_21_fu_390_p3;
wire   [24:0] x7_fu_402_p1;
wire   [24:0] p2y6_fu_398_p1;
wire   [15:0] tmp_23_fu_411_p3;
wire   [24:0] x1_fu_423_p1;
wire   [24:0] p2y1_fu_419_p1;
wire   [15:0] grp_fu_338_p2;
wire   [0:0] rev_fu_432_p2;
wire   [7:0] tmp_20_fu_437_p1;
wire   [15:0] grp_fu_351_p2;
wire   [0:0] rev1_fu_449_p2;
wire   [7:0] tmp_22_fu_454_p1;
wire   [15:0] grp_fu_364_p2;
wire   [0:0] rev2_fu_466_p2;
wire   [7:0] tmp_24_fu_471_p1;
wire   [31:0] grp_fu_219_p2;
wire   [31:0] grp_fu_224_p2;
wire   [31:0] grp_fu_229_p2;
wire   [8:0] tmp_7_cast_i_fu_513_p1;
wire   [8:0] tmp_8_cast_i_fu_516_p1;
wire   [11:0] tatol_pixs_fu_546_p0;
wire   [11:0] tatol_pixs_fu_546_p1;
wire   [7:0] grp_fu_553_p0;
wire   [8:0] grp_fu_553_p1;
wire   [11:0] grp_fu_553_p2;
reg    grp_fu_219_ap_start;
wire    grp_fu_219_ce;
reg    grp_fu_224_ap_start;
wire    grp_fu_224_ce;
reg    grp_fu_229_ap_start;
wire    grp_fu_229_ce;
reg    grp_fu_283_ce;
reg    grp_fu_296_ce;
reg    grp_fu_309_ce;
reg    grp_fu_338_ce;
reg    grp_fu_351_ce;
reg    grp_fu_364_ce;
reg   [41:0] ap_NS_fsm;
wire   [15:0] grp_fu_283_p00;
wire   [15:0] grp_fu_283_p10;
wire   [15:0] grp_fu_296_p00;
wire   [15:0] grp_fu_296_p10;
wire   [15:0] grp_fu_309_p00;
wire   [15:0] grp_fu_309_p10;
wire   [15:0] grp_fu_338_p10;
wire   [15:0] grp_fu_351_p10;
wire   [15:0] grp_fu_364_p10;
wire   [9:0] grp_fu_553_p00;
wire   [9:0] grp_fu_553_p10;
wire   [23:0] tatol_pixs_fu_546_p00;
wire   [23:0] tatol_pixs_fu_546_p10;


video_awb_udiv_32ns_24ns_32_36_seq #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 32 ))
video_awb_udiv_32ns_24ns_32_36_seq_U12(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .start( grp_fu_219_ap_start ),
    .done( grp_fu_219_ap_done ),
    .din0( sum_r_1_fu_96 ),
    .din1( grp_fu_219_p1 ),
    .ce( grp_fu_219_ce ),
    .dout( grp_fu_219_p2 )
);

video_awb_udiv_32ns_24ns_32_36_seq #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 32 ))
video_awb_udiv_32ns_24ns_32_36_seq_U13(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .start( grp_fu_224_ap_start ),
    .done( grp_fu_224_ap_done ),
    .din0( sum_g_1_fu_92 ),
    .din1( grp_fu_224_p1 ),
    .ce( grp_fu_224_ce ),
    .dout( grp_fu_224_p2 )
);

video_awb_udiv_32ns_24ns_32_36_seq #(
    .ID( 1 ),
    .NUM_STAGE( 36 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 32 ))
video_awb_udiv_32ns_24ns_32_36_seq_U14(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .start( grp_fu_229_ap_start ),
    .done( grp_fu_229_ap_done ),
    .din0( sum_b_1_fu_88 ),
    .din1( grp_fu_229_p1 ),
    .ce( grp_fu_229_ce ),
    .dout( grp_fu_229_p2 )
);

video_awb_mul_8ns_10ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 16 ))
video_awb_mul_8ns_10ns_16_3_U15(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_283_p0 ),
    .din1( grp_fu_283_p1 ),
    .ce( grp_fu_283_ce ),
    .dout( grp_fu_283_p2 )
);

video_awb_mul_8ns_10ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 16 ))
video_awb_mul_8ns_10ns_16_3_U16(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_296_p0 ),
    .din1( grp_fu_296_p1 ),
    .ce( grp_fu_296_ce ),
    .dout( grp_fu_296_p2 )
);

video_awb_mul_8ns_10ns_16_3 #(
    .ID( 1 ),
    .NUM_STAGE( 3 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 16 ))
video_awb_mul_8ns_10ns_16_3_U17(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_309_p0 ),
    .din1( grp_fu_309_p1 ),
    .ce( grp_fu_309_ce ),
    .dout( grp_fu_309_p2 )
);

video_awb_udiv_16ns_8ns_16_20 #(
    .ID( 1 ),
    .NUM_STAGE( 20 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
video_awb_udiv_16ns_8ns_16_20_U18(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( tmp_12_reg_680 ),
    .din1( grp_fu_338_p1 ),
    .ce( grp_fu_338_ce ),
    .dout( grp_fu_338_p2 )
);

video_awb_udiv_16ns_8ns_16_20 #(
    .ID( 1 ),
    .NUM_STAGE( 20 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
video_awb_udiv_16ns_8ns_16_20_U19(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( tmp_15_reg_686 ),
    .din1( grp_fu_351_p1 ),
    .ce( grp_fu_351_ce ),
    .dout( grp_fu_351_p2 )
);

video_awb_udiv_16ns_8ns_16_20 #(
    .ID( 1 ),
    .NUM_STAGE( 20 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 16 ))
video_awb_udiv_16ns_8ns_16_20_U20(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( tmp_18_reg_692 ),
    .din1( grp_fu_364_p1 ),
    .ce( grp_fu_364_ce ),
    .dout( grp_fu_364_p2 )
);

video_awb_mul_mul_12ns_12ns_24_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 12 ),
    .din1_WIDTH( 12 ),
    .dout_WIDTH( 24 ))
video_awb_mul_mul_12ns_12ns_24_1_U21(
    .din0( tatol_pixs_fu_546_p0 ),
    .din1( tatol_pixs_fu_546_p1 ),
    .dout( tatol_pixs_fu_546_p2 )
);

video_awb_am_addmul_8ns_9ns_12ns_22_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 9 ),
    .din2_WIDTH( 12 ),
    .dout_WIDTH( 22 ))
video_awb_am_addmul_8ns_9ns_12ns_22_1_U22(
    .din0( grp_fu_553_p0 ),
    .din1( grp_fu_553_p1 ),
    .din2( grp_fu_553_p2 ),
    .dout( grp_fu_553_p3 )
);



always @ (posedge ap_clk) begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_done_reg
    if (ap_rst == 1'b1) begin
        ap_done_reg <= ap_const_logic_0;
    end else begin
        if ((ap_const_logic_1 == ap_continue)) begin
            ap_done_reg <= ap_const_logic_0;
        end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st67_fsm_41)) begin
            ap_done_reg <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it0
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & ~(ap_const_lv1_0 == exitcond_i_fu_234_p2))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_0;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond4_i_fu_208_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it0 <= ap_const_logic_1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it1
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & (ap_const_lv1_0 == exitcond_i_fu_234_p2))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_1;
        end else if ((((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond4_i_fu_208_p2 == ap_const_lv1_0)) | ((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & ~(ap_const_lv1_0 == exitcond_i_fu_234_p2)))) begin
            ap_reg_ppiten_pp0_it1 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it10
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it10 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it10 <= ap_reg_ppiten_pp0_it9;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it11
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it11 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it11 <= ap_reg_ppiten_pp0_it10;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it12
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it12 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it12 <= ap_reg_ppiten_pp0_it11;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it13
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it13 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it13 <= ap_reg_ppiten_pp0_it12;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it14
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it14 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it14 <= ap_reg_ppiten_pp0_it13;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it15
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it15 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it15 <= ap_reg_ppiten_pp0_it14;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it16
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it16 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it16 <= ap_reg_ppiten_pp0_it15;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it17
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it17 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it17 <= ap_reg_ppiten_pp0_it16;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it18
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it18 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it18 <= ap_reg_ppiten_pp0_it17;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it19
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it19 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it19 <= ap_reg_ppiten_pp0_it18;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it2
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it2 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it2 <= ap_reg_ppiten_pp0_it1;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it20
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it20 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it20 <= ap_reg_ppiten_pp0_it19;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it21
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it21 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it21 <= ap_reg_ppiten_pp0_it20;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it22
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it22 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it22 <= ap_reg_ppiten_pp0_it21;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it23
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it23 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it23 <= ap_reg_ppiten_pp0_it22;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it24
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it24 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it24 <= ap_reg_ppiten_pp0_it23;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it25
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it25 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it25 <= ap_reg_ppiten_pp0_it24;
        end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond4_i_fu_208_p2 == ap_const_lv1_0))) begin
            ap_reg_ppiten_pp0_it25 <= ap_const_logic_0;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it3
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it3 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it3 <= ap_reg_ppiten_pp0_it2;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it4
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it4 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it4 <= ap_reg_ppiten_pp0_it3;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it5
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it5 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it5 <= ap_reg_ppiten_pp0_it4;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it6
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it6 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it6 <= ap_reg_ppiten_pp0_it5;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it7
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it7 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it7 <= ap_reg_ppiten_pp0_it6;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it8
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it8 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it8 <= ap_reg_ppiten_pp0_it7;
        end
    end
end

always @ (posedge ap_clk) begin : ap_ret_ap_reg_ppiten_pp0_it9
    if (ap_rst == 1'b1) begin
        ap_reg_ppiten_pp0_it9 <= ap_const_logic_0;
    end else begin
        if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
            ap_reg_ppiten_pp0_it9 <= ap_reg_ppiten_pp0_it8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & (ap_const_lv1_0 == exitcond_i_fu_234_p2))) begin
        col_i_reg_162 <= col_fu_239_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & (exitcond4_i_fu_208_p2 == ap_const_lv1_0))) begin
        col_i_reg_162 <= ap_const_lv12_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st29_fsm_3)) begin
        row_i_reg_151 <= row_reg_603;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_107)) begin
        row_i_reg_151 <= ap_const_lv12_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it1))) begin
        sum_b_1_fu_88 <= sum_b_fu_266_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_107)) begin
        sum_b_1_fu_88 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it1))) begin
        sum_g_1_fu_92 <= sum_g_fu_257_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_107)) begin
        sum_g_1_fu_92 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_reg_ppiten_pp0_it2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it1))) begin
        sum_r_1_fu_96 <= sum_r_fu_248_p2;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~ap_sig_bdd_107)) begin
        sum_r_1_fu_96 <= ap_const_lv32_0;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st67_fsm_41)) begin
        K <= {{mul_reg_763[ap_const_lv32_15 : ap_const_lv32_C]}};
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it1 <= exitcond_i_reg_623;
        exitcond_i_reg_623 <= exitcond_i_fu_234_p2;
    end
end

always @ (posedge ap_clk) begin
    if (~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25)))) begin
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it10 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it9;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it11 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it10;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it12 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it11;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it13 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it12;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it14 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it13;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it15 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it14;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it16 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it15;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it17 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it16;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it18 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it17;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it19 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it18;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it2 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it1;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it20 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it19;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it21 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it20;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it22 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it21;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it23 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it22;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it24 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it23;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it3 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it2;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it4 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it3;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it5 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it4;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it6 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it5;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it7 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it6;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it8 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it7;
        ap_reg_ppstg_exitcond_i_reg_623_pp0_it9 <= ap_reg_ppstg_exitcond_i_reg_623_pp0_it8;
        ap_reg_ppstg_ult1_reg_718_pp0_it10 <= ap_reg_ppstg_ult1_reg_718_pp0_it9;
        ap_reg_ppstg_ult1_reg_718_pp0_it11 <= ap_reg_ppstg_ult1_reg_718_pp0_it10;
        ap_reg_ppstg_ult1_reg_718_pp0_it12 <= ap_reg_ppstg_ult1_reg_718_pp0_it11;
        ap_reg_ppstg_ult1_reg_718_pp0_it13 <= ap_reg_ppstg_ult1_reg_718_pp0_it12;
        ap_reg_ppstg_ult1_reg_718_pp0_it14 <= ap_reg_ppstg_ult1_reg_718_pp0_it13;
        ap_reg_ppstg_ult1_reg_718_pp0_it15 <= ap_reg_ppstg_ult1_reg_718_pp0_it14;
        ap_reg_ppstg_ult1_reg_718_pp0_it16 <= ap_reg_ppstg_ult1_reg_718_pp0_it15;
        ap_reg_ppstg_ult1_reg_718_pp0_it17 <= ap_reg_ppstg_ult1_reg_718_pp0_it16;
        ap_reg_ppstg_ult1_reg_718_pp0_it18 <= ap_reg_ppstg_ult1_reg_718_pp0_it17;
        ap_reg_ppstg_ult1_reg_718_pp0_it19 <= ap_reg_ppstg_ult1_reg_718_pp0_it18;
        ap_reg_ppstg_ult1_reg_718_pp0_it20 <= ap_reg_ppstg_ult1_reg_718_pp0_it19;
        ap_reg_ppstg_ult1_reg_718_pp0_it21 <= ap_reg_ppstg_ult1_reg_718_pp0_it20;
        ap_reg_ppstg_ult1_reg_718_pp0_it22 <= ap_reg_ppstg_ult1_reg_718_pp0_it21;
        ap_reg_ppstg_ult1_reg_718_pp0_it23 <= ap_reg_ppstg_ult1_reg_718_pp0_it22;
        ap_reg_ppstg_ult1_reg_718_pp0_it6 <= ult1_reg_718;
        ap_reg_ppstg_ult1_reg_718_pp0_it7 <= ap_reg_ppstg_ult1_reg_718_pp0_it6;
        ap_reg_ppstg_ult1_reg_718_pp0_it8 <= ap_reg_ppstg_ult1_reg_718_pp0_it7;
        ap_reg_ppstg_ult1_reg_718_pp0_it9 <= ap_reg_ppstg_ult1_reg_718_pp0_it8;
        ap_reg_ppstg_ult2_reg_723_pp0_it10 <= ap_reg_ppstg_ult2_reg_723_pp0_it9;
        ap_reg_ppstg_ult2_reg_723_pp0_it11 <= ap_reg_ppstg_ult2_reg_723_pp0_it10;
        ap_reg_ppstg_ult2_reg_723_pp0_it12 <= ap_reg_ppstg_ult2_reg_723_pp0_it11;
        ap_reg_ppstg_ult2_reg_723_pp0_it13 <= ap_reg_ppstg_ult2_reg_723_pp0_it12;
        ap_reg_ppstg_ult2_reg_723_pp0_it14 <= ap_reg_ppstg_ult2_reg_723_pp0_it13;
        ap_reg_ppstg_ult2_reg_723_pp0_it15 <= ap_reg_ppstg_ult2_reg_723_pp0_it14;
        ap_reg_ppstg_ult2_reg_723_pp0_it16 <= ap_reg_ppstg_ult2_reg_723_pp0_it15;
        ap_reg_ppstg_ult2_reg_723_pp0_it17 <= ap_reg_ppstg_ult2_reg_723_pp0_it16;
        ap_reg_ppstg_ult2_reg_723_pp0_it18 <= ap_reg_ppstg_ult2_reg_723_pp0_it17;
        ap_reg_ppstg_ult2_reg_723_pp0_it19 <= ap_reg_ppstg_ult2_reg_723_pp0_it18;
        ap_reg_ppstg_ult2_reg_723_pp0_it20 <= ap_reg_ppstg_ult2_reg_723_pp0_it19;
        ap_reg_ppstg_ult2_reg_723_pp0_it21 <= ap_reg_ppstg_ult2_reg_723_pp0_it20;
        ap_reg_ppstg_ult2_reg_723_pp0_it22 <= ap_reg_ppstg_ult2_reg_723_pp0_it21;
        ap_reg_ppstg_ult2_reg_723_pp0_it23 <= ap_reg_ppstg_ult2_reg_723_pp0_it22;
        ap_reg_ppstg_ult2_reg_723_pp0_it6 <= ult2_reg_723;
        ap_reg_ppstg_ult2_reg_723_pp0_it7 <= ap_reg_ppstg_ult2_reg_723_pp0_it6;
        ap_reg_ppstg_ult2_reg_723_pp0_it8 <= ap_reg_ppstg_ult2_reg_723_pp0_it7;
        ap_reg_ppstg_ult2_reg_723_pp0_it9 <= ap_reg_ppstg_ult2_reg_723_pp0_it8;
        ap_reg_ppstg_ult_reg_713_pp0_it10 <= ap_reg_ppstg_ult_reg_713_pp0_it9;
        ap_reg_ppstg_ult_reg_713_pp0_it11 <= ap_reg_ppstg_ult_reg_713_pp0_it10;
        ap_reg_ppstg_ult_reg_713_pp0_it12 <= ap_reg_ppstg_ult_reg_713_pp0_it11;
        ap_reg_ppstg_ult_reg_713_pp0_it13 <= ap_reg_ppstg_ult_reg_713_pp0_it12;
        ap_reg_ppstg_ult_reg_713_pp0_it14 <= ap_reg_ppstg_ult_reg_713_pp0_it13;
        ap_reg_ppstg_ult_reg_713_pp0_it15 <= ap_reg_ppstg_ult_reg_713_pp0_it14;
        ap_reg_ppstg_ult_reg_713_pp0_it16 <= ap_reg_ppstg_ult_reg_713_pp0_it15;
        ap_reg_ppstg_ult_reg_713_pp0_it17 <= ap_reg_ppstg_ult_reg_713_pp0_it16;
        ap_reg_ppstg_ult_reg_713_pp0_it18 <= ap_reg_ppstg_ult_reg_713_pp0_it17;
        ap_reg_ppstg_ult_reg_713_pp0_it19 <= ap_reg_ppstg_ult_reg_713_pp0_it18;
        ap_reg_ppstg_ult_reg_713_pp0_it20 <= ap_reg_ppstg_ult_reg_713_pp0_it19;
        ap_reg_ppstg_ult_reg_713_pp0_it21 <= ap_reg_ppstg_ult_reg_713_pp0_it20;
        ap_reg_ppstg_ult_reg_713_pp0_it22 <= ap_reg_ppstg_ult_reg_713_pp0_it21;
        ap_reg_ppstg_ult_reg_713_pp0_it23 <= ap_reg_ppstg_ult_reg_713_pp0_it22;
        ap_reg_ppstg_ult_reg_713_pp0_it6 <= ult_reg_713;
        ap_reg_ppstg_ult_reg_713_pp0_it7 <= ap_reg_ppstg_ult_reg_713_pp0_it6;
        ap_reg_ppstg_ult_reg_713_pp0_it8 <= ap_reg_ppstg_ult_reg_713_pp0_it7;
        ap_reg_ppstg_ult_reg_713_pp0_it9 <= ap_reg_ppstg_ult_reg_713_pp0_it8;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st64_fsm_38) & ~((ap_const_logic_0 == grp_fu_219_ap_done) | (ap_const_logic_0 == grp_fu_224_ap_done) | (ap_const_logic_0 == grp_fu_229_ap_done)))) begin
        aver_b <= tmp_3_fu_503_p1;
        aver_g <= tmp_2_fu_493_p1;
        aver_r <= tmp_fu_483_p1;
        tmp_2_reg_748 <= tmp_2_fu_493_p1;
        tmp_3_reg_753 <= tmp_3_fu_503_p1;
        tmp_reg_743 <= tmp_fu_483_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st66_fsm_40)) begin
        mul_reg_763 <= grp_fu_553_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        row_reg_603 <= row_fu_213_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st65_fsm_39)) begin
        tmp_10_i_reg_758 <= tmp_10_i_fu_519_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it3))) begin
        tmp_12_reg_680 <= grp_fu_283_p2;
        tmp_15_reg_686 <= grp_fu_296_p2;
        tmp_18_reg_692 <= grp_fu_309_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_i_reg_623) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        tmp_25_reg_632 <= src_data_stream_0_V_dout;
        tmp_26_reg_638 <= src_data_stream_1_V_dout;
        tmp_9_reg_644 <= src_data_stream_2_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it23))) begin
        tmp_5_reg_738 <= tmp_5_fu_475_p3;
        tmp_6_reg_733 <= tmp_6_fu_458_p3;
        tmp_7_reg_728 <= tmp_7_fu_441_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it4))) begin
        ult1_reg_718 <= ult1_fu_405_p2;
        ult2_reg_723 <= ult2_fu_426_p2;
        ult_reg_713 <= ult_fu_384_p2;
    end
end

always @ (ap_done_reg or ap_sig_cseq_ST_st67_fsm_41) begin
    if (((ap_const_logic_1 == ap_done_reg) | (ap_const_logic_1 == ap_sig_cseq_ST_st67_fsm_41))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0) begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_st67_fsm_41) begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st67_fsm_41)) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_142) begin
    if (ap_sig_bdd_142) begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_pp0_stg0_fsm_2 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_61) begin
    if (ap_sig_bdd_61) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_542) begin
    if (ap_sig_bdd_542) begin
        ap_sig_cseq_ST_st29_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st29_fsm_3 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_121) begin
    if (ap_sig_bdd_121) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_494) begin
    if (ap_sig_bdd_494) begin
        ap_sig_cseq_ST_st64_fsm_38 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st64_fsm_38 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_517) begin
    if (ap_sig_bdd_517) begin
        ap_sig_cseq_ST_st65_fsm_39 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st65_fsm_39 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_526) begin
    if (ap_sig_bdd_526) begin
        ap_sig_cseq_ST_st66_fsm_40 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st66_fsm_40 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_563) begin
    if (ap_sig_bdd_563) begin
        ap_sig_cseq_ST_st67_fsm_41 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st67_fsm_41 = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_i_reg_623_pp0_it24 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it24) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        dst_data_stream_0_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_0_V_write = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_i_reg_623_pp0_it24 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it24) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        dst_data_stream_1_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_1_V_write = ap_const_logic_0;
    end
end

always @ (ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_reg_ppstg_exitcond_i_reg_623_pp0_it24 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it24) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        dst_data_stream_2_V_write = ap_const_logic_1;
    end else begin
        dst_data_stream_2_V_write = ap_const_logic_0;
    end
end

always @ (exitcond4_i_fu_208_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond4_i_fu_208_p2 == ap_const_lv1_0))) begin
        grp_fu_219_ap_start = ap_const_logic_1;
    end else begin
        grp_fu_219_ap_start = ap_const_logic_0;
    end
end

always @ (exitcond4_i_fu_208_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond4_i_fu_208_p2 == ap_const_lv1_0))) begin
        grp_fu_224_ap_start = ap_const_logic_1;
    end else begin
        grp_fu_224_ap_start = ap_const_logic_0;
    end
end

always @ (exitcond4_i_fu_208_p2 or ap_sig_cseq_ST_st2_fsm_1) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~(exitcond4_i_fu_208_p2 == ap_const_lv1_0))) begin
        grp_fu_229_ap_start = ap_const_logic_1;
    end else begin
        grp_fu_229_ap_start = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        grp_fu_283_ce = ap_const_logic_1;
    end else begin
        grp_fu_283_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        grp_fu_296_ce = ap_const_logic_1;
    end else begin
        grp_fu_296_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        grp_fu_309_ce = ap_const_logic_1;
    end else begin
        grp_fu_309_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        grp_fu_338_ce = ap_const_logic_1;
    end else begin
        grp_fu_338_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        grp_fu_351_ce = ap_const_logic_1;
    end else begin
        grp_fu_351_ce = ap_const_logic_0;
    end
end

always @ (ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        grp_fu_364_ce = ap_const_logic_1;
    end else begin
        grp_fu_364_ce = ap_const_logic_0;
    end
end

always @ (exitcond_i_reg_623 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_i_reg_623) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        src_data_stream_0_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_0_V_read = ap_const_logic_0;
    end
end

always @ (exitcond_i_reg_623 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_i_reg_623) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        src_data_stream_1_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_1_V_read = ap_const_logic_0;
    end
end

always @ (exitcond_i_reg_623 or ap_sig_cseq_ST_pp0_stg0_fsm_2 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25) begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_pp0_stg0_fsm_2) & (ap_const_lv1_0 == exitcond_i_reg_623) & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))))) begin
        src_data_stream_2_V_read = ap_const_logic_1;
    end else begin
        src_data_stream_2_V_read = ap_const_logic_0;
    end
end
always @ (ap_CS_fsm or ap_sig_bdd_107 or exitcond4_i_fu_208_p2 or exitcond_i_fu_234_p2 or ap_reg_ppiten_pp0_it0 or ap_sig_bdd_155 or ap_reg_ppiten_pp0_it1 or ap_reg_ppiten_pp0_it24 or ap_sig_bdd_215 or ap_reg_ppiten_pp0_it25 or grp_fu_219_ap_done or grp_fu_224_ap_done or grp_fu_229_ap_done) begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if (~ap_sig_bdd_107) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if ((exitcond4_i_fu_208_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st30_fsm_4;
            end
        end
        ap_ST_pp0_stg0_fsm_2 : 
        begin
            if ((~((ap_const_logic_1 == ap_reg_ppiten_pp0_it25) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it24)) & ~((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & ~(ap_const_lv1_0 == exitcond_i_fu_234_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end else if ((((ap_const_logic_1 == ap_reg_ppiten_pp0_it25) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it24)) | ((ap_const_logic_1 == ap_reg_ppiten_pp0_it0) & ~((ap_sig_bdd_155 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it1)) | (ap_sig_bdd_215 & (ap_const_logic_1 == ap_reg_ppiten_pp0_it25))) & ~(ap_const_lv1_0 == exitcond_i_fu_234_p2) & ~(ap_const_logic_1 == ap_reg_ppiten_pp0_it1)))) begin
                ap_NS_fsm = ap_ST_st29_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_pp0_stg0_fsm_2;
            end
        end
        ap_ST_st29_fsm_3 : 
        begin
            ap_NS_fsm = ap_ST_st2_fsm_1;
        end
        ap_ST_st30_fsm_4 : 
        begin
            ap_NS_fsm = ap_ST_st31_fsm_5;
        end
        ap_ST_st31_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st32_fsm_6;
        end
        ap_ST_st32_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st33_fsm_7;
        end
        ap_ST_st33_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st34_fsm_8;
        end
        ap_ST_st34_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st35_fsm_9;
        end
        ap_ST_st35_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st36_fsm_10;
        end
        ap_ST_st36_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st37_fsm_11;
        end
        ap_ST_st37_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st38_fsm_12;
        end
        ap_ST_st38_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st39_fsm_13;
        end
        ap_ST_st39_fsm_13 : 
        begin
            ap_NS_fsm = ap_ST_st40_fsm_14;
        end
        ap_ST_st40_fsm_14 : 
        begin
            ap_NS_fsm = ap_ST_st41_fsm_15;
        end
        ap_ST_st41_fsm_15 : 
        begin
            ap_NS_fsm = ap_ST_st42_fsm_16;
        end
        ap_ST_st42_fsm_16 : 
        begin
            ap_NS_fsm = ap_ST_st43_fsm_17;
        end
        ap_ST_st43_fsm_17 : 
        begin
            ap_NS_fsm = ap_ST_st44_fsm_18;
        end
        ap_ST_st44_fsm_18 : 
        begin
            ap_NS_fsm = ap_ST_st45_fsm_19;
        end
        ap_ST_st45_fsm_19 : 
        begin
            ap_NS_fsm = ap_ST_st46_fsm_20;
        end
        ap_ST_st46_fsm_20 : 
        begin
            ap_NS_fsm = ap_ST_st47_fsm_21;
        end
        ap_ST_st47_fsm_21 : 
        begin
            ap_NS_fsm = ap_ST_st48_fsm_22;
        end
        ap_ST_st48_fsm_22 : 
        begin
            ap_NS_fsm = ap_ST_st49_fsm_23;
        end
        ap_ST_st49_fsm_23 : 
        begin
            ap_NS_fsm = ap_ST_st50_fsm_24;
        end
        ap_ST_st50_fsm_24 : 
        begin
            ap_NS_fsm = ap_ST_st51_fsm_25;
        end
        ap_ST_st51_fsm_25 : 
        begin
            ap_NS_fsm = ap_ST_st52_fsm_26;
        end
        ap_ST_st52_fsm_26 : 
        begin
            ap_NS_fsm = ap_ST_st53_fsm_27;
        end
        ap_ST_st53_fsm_27 : 
        begin
            ap_NS_fsm = ap_ST_st54_fsm_28;
        end
        ap_ST_st54_fsm_28 : 
        begin
            ap_NS_fsm = ap_ST_st55_fsm_29;
        end
        ap_ST_st55_fsm_29 : 
        begin
            ap_NS_fsm = ap_ST_st56_fsm_30;
        end
        ap_ST_st56_fsm_30 : 
        begin
            ap_NS_fsm = ap_ST_st57_fsm_31;
        end
        ap_ST_st57_fsm_31 : 
        begin
            ap_NS_fsm = ap_ST_st58_fsm_32;
        end
        ap_ST_st58_fsm_32 : 
        begin
            ap_NS_fsm = ap_ST_st59_fsm_33;
        end
        ap_ST_st59_fsm_33 : 
        begin
            ap_NS_fsm = ap_ST_st60_fsm_34;
        end
        ap_ST_st60_fsm_34 : 
        begin
            ap_NS_fsm = ap_ST_st61_fsm_35;
        end
        ap_ST_st61_fsm_35 : 
        begin
            ap_NS_fsm = ap_ST_st62_fsm_36;
        end
        ap_ST_st62_fsm_36 : 
        begin
            ap_NS_fsm = ap_ST_st63_fsm_37;
        end
        ap_ST_st63_fsm_37 : 
        begin
            ap_NS_fsm = ap_ST_st64_fsm_38;
        end
        ap_ST_st64_fsm_38 : 
        begin
            if (~((ap_const_logic_0 == grp_fu_219_ap_done) | (ap_const_logic_0 == grp_fu_224_ap_done) | (ap_const_logic_0 == grp_fu_229_ap_done))) begin
                ap_NS_fsm = ap_ST_st65_fsm_39;
            end else begin
                ap_NS_fsm = ap_ST_st64_fsm_38;
            end
        end
        ap_ST_st65_fsm_39 : 
        begin
            ap_NS_fsm = ap_ST_st66_fsm_40;
        end
        ap_ST_st66_fsm_40 : 
        begin
            ap_NS_fsm = ap_ST_st67_fsm_41;
        end
        ap_ST_st67_fsm_41 : 
        begin
            ap_NS_fsm = ap_ST_st1_fsm_0;
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end



always @ (ap_start or ap_done_reg) begin
    ap_sig_bdd_107 = ((ap_start == ap_const_logic_0) | (ap_done_reg == ap_const_logic_1));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_121 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_142 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end


always @ (src_data_stream_0_V_empty_n or src_data_stream_1_V_empty_n or src_data_stream_2_V_empty_n or exitcond_i_reg_623) begin
    ap_sig_bdd_155 = (((src_data_stream_0_V_empty_n == ap_const_logic_0) & (ap_const_lv1_0 == exitcond_i_reg_623)) | ((ap_const_lv1_0 == exitcond_i_reg_623) & (src_data_stream_1_V_empty_n == ap_const_logic_0)) | ((ap_const_lv1_0 == exitcond_i_reg_623) & (src_data_stream_2_V_empty_n == ap_const_logic_0)));
end


always @ (dst_data_stream_0_V_full_n or dst_data_stream_1_V_full_n or dst_data_stream_2_V_full_n or ap_reg_ppstg_exitcond_i_reg_623_pp0_it24) begin
    ap_sig_bdd_215 = (((dst_data_stream_0_V_full_n == ap_const_logic_0) & (ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it24)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it24) & (dst_data_stream_1_V_full_n == ap_const_logic_0)) | ((ap_const_lv1_0 == ap_reg_ppstg_exitcond_i_reg_623_pp0_it24) & (dst_data_stream_2_V_full_n == ap_const_logic_0)));
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_494 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_26]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_517 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_27]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_526 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_28]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_542 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_563 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_29]);
end


always @ (ap_CS_fsm) begin
    ap_sig_bdd_61 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

assign col_fu_239_p2 = (col_i_reg_162 + ap_const_lv12_1);

assign dst_data_stream_0_V_din = tmp_5_reg_738;

assign dst_data_stream_1_V_din = tmp_6_reg_733;

assign dst_data_stream_2_V_din = tmp_7_reg_728;

assign exitcond4_i_fu_208_p2 = (row_i_reg_151 == src_rows_V? 1'b1: 1'b0);

assign exitcond_i_fu_234_p2 = (col_i_reg_162 == src_cols_V? 1'b1: 1'b0);

assign grp_fu_219_ce = ap_const_logic_1;

assign grp_fu_219_p1 = tatol_pixs_cast_i_fu_190_p1;

assign grp_fu_224_ce = ap_const_logic_1;

assign grp_fu_224_p1 = tatol_pixs_cast_i_fu_190_p1;

assign grp_fu_229_ce = ap_const_logic_1;

assign grp_fu_229_p1 = tatol_pixs_cast_i_fu_190_p1;

assign grp_fu_283_p0 = grp_fu_283_p00;

assign grp_fu_283_p00 = tmp_9_reg_644;

assign grp_fu_283_p1 = grp_fu_283_p10;

assign grp_fu_283_p10 = K;

assign grp_fu_296_p0 = grp_fu_296_p00;

assign grp_fu_296_p00 = tmp_26_reg_638;

assign grp_fu_296_p1 = grp_fu_296_p10;

assign grp_fu_296_p10 = K;

assign grp_fu_309_p0 = grp_fu_309_p00;

assign grp_fu_309_p00 = tmp_25_reg_632;

assign grp_fu_309_p1 = grp_fu_309_p10;

assign grp_fu_309_p10 = K;

assign grp_fu_338_p1 = grp_fu_338_p10;

assign grp_fu_338_p10 = aver_r;

assign grp_fu_351_p1 = grp_fu_351_p10;

assign grp_fu_351_p10 = aver_g;

assign grp_fu_364_p1 = grp_fu_364_p10;

assign grp_fu_364_p10 = aver_b;

assign grp_fu_553_p0 = grp_fu_553_p00;

assign grp_fu_553_p00 = tmp_3_reg_753;

assign grp_fu_553_p1 = grp_fu_553_p10;

assign grp_fu_553_p10 = tmp_10_i_reg_758;

assign grp_fu_553_p2 = ap_const_lv22_556;

assign p2y1_fu_419_p1 = tmp_23_fu_411_p3;

assign p2y6_fu_398_p1 = tmp_21_fu_390_p3;

assign p2y_fu_377_p1 = tmp_19_fu_369_p3;

assign rev1_fu_449_p2 = (ap_reg_ppstg_ult1_reg_718_pp0_it23 ^ ap_const_lv1_1);

assign rev2_fu_466_p2 = (ap_reg_ppstg_ult2_reg_723_pp0_it23 ^ ap_const_lv1_1);

assign rev_fu_432_p2 = (ap_reg_ppstg_ult_reg_713_pp0_it23 ^ ap_const_lv1_1);

assign row_fu_213_p2 = (row_i_reg_151 + ap_const_lv12_1);

assign sum_b_fu_266_p2 = (sum_b_1_fu_88 + tmp_16_i_fu_263_p1);

assign sum_g_fu_257_p2 = (sum_g_1_fu_92 + tmp_15_i_fu_254_p1);

assign sum_r_fu_248_p2 = (sum_r_1_fu_96 + tmp_14_i_fu_245_p1);

assign tatol_pixs_cast_i_fu_190_p1 = tatol_pixs_fu_546_p2;

assign tatol_pixs_fu_546_p0 = tatol_pixs_fu_546_p00;

assign tatol_pixs_fu_546_p00 = src_cols_V;

assign tatol_pixs_fu_546_p1 = tatol_pixs_fu_546_p10;

assign tatol_pixs_fu_546_p10 = src_rows_V;

assign tmp_10_i_fu_519_p2 = (tmp_7_cast_i_fu_513_p1 + tmp_8_cast_i_fu_516_p1);

assign tmp_14_i_fu_245_p1 = tmp_9_reg_644;

assign tmp_15_i_fu_254_p1 = tmp_26_reg_638;

assign tmp_16_i_fu_263_p1 = tmp_25_reg_632;

assign tmp_19_fu_369_p3 = {{aver_r}, {ap_const_lv8_0}};

assign tmp_20_fu_437_p1 = grp_fu_338_p2[7:0];

assign tmp_21_fu_390_p3 = {{aver_g}, {ap_const_lv8_0}};

assign tmp_22_fu_454_p1 = grp_fu_351_p2[7:0];

assign tmp_23_fu_411_p3 = {{aver_b}, {ap_const_lv8_0}};

assign tmp_24_fu_471_p1 = grp_fu_364_p2[7:0];

assign tmp_2_fu_493_p1 = grp_fu_224_p2[7:0];

assign tmp_3_fu_503_p1 = grp_fu_229_p2[7:0];

assign tmp_5_fu_475_p3 = ((rev2_fu_466_p2[0:0] === 1'b1) ? ap_const_lv8_FF : tmp_24_fu_471_p1);

assign tmp_6_fu_458_p3 = ((rev1_fu_449_p2[0:0] === 1'b1) ? ap_const_lv8_FF : tmp_22_fu_454_p1);

assign tmp_7_cast_i_fu_513_p1 = tmp_reg_743;

assign tmp_7_fu_441_p3 = ((rev_fu_432_p2[0:0] === 1'b1) ? ap_const_lv8_FF : tmp_20_fu_437_p1);

assign tmp_8_cast_i_fu_516_p1 = tmp_2_reg_748;

assign tmp_fu_483_p1 = grp_fu_219_p2[7:0];

assign ult1_fu_405_p2 = (x7_fu_402_p1 < p2y6_fu_398_p1? 1'b1: 1'b0);

assign ult2_fu_426_p2 = (x1_fu_423_p1 < p2y1_fu_419_p1? 1'b1: 1'b0);

assign ult_fu_384_p2 = (x_fu_381_p1 < p2y_fu_377_p1? 1'b1: 1'b0);

assign x1_fu_423_p1 = tmp_18_reg_692;

assign x7_fu_402_p1 = tmp_15_reg_686;

assign x_fu_381_p1 = tmp_12_reg_680;


endmodule //video_awb_awb

