// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xscaler.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XScaler_CfgInitialize(XScaler *InstancePtr, XScaler_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XScaler_Start(XScaler *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XScaler_IsDone(XScaler *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XScaler_IsIdle(XScaler *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XScaler_IsReady(XScaler *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XScaler_EnableAutoRestart(XScaler *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XScaler_DisableAutoRestart(XScaler *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XScaler_Set_src_rows(XScaler *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_SRC_ROWS_DATA, Data);
}

u32 XScaler_Get_src_rows(XScaler *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_SRC_ROWS_DATA);
    return Data;
}

void XScaler_Set_src_cols(XScaler *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_SRC_COLS_DATA, Data);
}

u32 XScaler_Get_src_cols(XScaler *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_SRC_COLS_DATA);
    return Data;
}

void XScaler_Set_dst_cols(XScaler *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_DST_COLS_DATA, Data);
}

u32 XScaler_Get_dst_cols(XScaler *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_DST_COLS_DATA);
    return Data;
}

void XScaler_Set_dst_rows(XScaler *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_DST_ROWS_DATA, Data);
}

u32 XScaler_Get_dst_rows(XScaler *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_DST_ROWS_DATA);
    return Data;
}

void XScaler_InterruptGlobalEnable(XScaler *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_GIE, 1);
}

void XScaler_InterruptGlobalDisable(XScaler *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_GIE, 0);
}

void XScaler_InterruptEnable(XScaler *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_IER);
    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XScaler_InterruptDisable(XScaler *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_IER);
    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XScaler_InterruptClear(XScaler *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XScaler_WriteReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XScaler_InterruptGetEnabled(XScaler *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_IER);
}

u32 XScaler_InterruptGetStatus(XScaler *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XScaler_ReadReg(InstancePtr->Control_bus_BaseAddress, XSCALER_CONTROL_BUS_ADDR_ISR);
}

