// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// CONTROL_BUS
// 0x00 : Control signals
//        bit 0  - ap_start (Read/Write/COH)
//        bit 1  - ap_done (Read/COR)
//        bit 2  - ap_idle (Read)
//        bit 3  - ap_ready (Read)
//        bit 7  - auto_restart (Read/Write)
//        others - reserved
// 0x04 : Global Interrupt Enable Register
//        bit 0  - Global Interrupt Enable (Read/Write)
//        others - reserved
// 0x08 : IP Interrupt Enable Register (Read/Write)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x0c : IP Interrupt Status Register (Read/TOW)
//        bit 0  - Channel 0 (ap_done)
//        bit 1  - Channel 1 (ap_ready)
//        others - reserved
// 0x14 : Data signal of src_rows
//        bit 31~0 - src_rows[31:0] (Read/Write)
// 0x18 : reserved
// 0x1c : Data signal of src_cols
//        bit 31~0 - src_cols[31:0] (Read/Write)
// 0x20 : reserved
// 0x24 : Data signal of dst_cols
//        bit 31~0 - dst_cols[31:0] (Read/Write)
// 0x28 : reserved
// 0x2c : Data signal of dst_rows
//        bit 31~0 - dst_rows[31:0] (Read/Write)
// 0x30 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSCALER_CONTROL_BUS_ADDR_AP_CTRL       0x00
#define XSCALER_CONTROL_BUS_ADDR_GIE           0x04
#define XSCALER_CONTROL_BUS_ADDR_IER           0x08
#define XSCALER_CONTROL_BUS_ADDR_ISR           0x0c
#define XSCALER_CONTROL_BUS_ADDR_SRC_ROWS_DATA 0x14
#define XSCALER_CONTROL_BUS_BITS_SRC_ROWS_DATA 32
#define XSCALER_CONTROL_BUS_ADDR_SRC_COLS_DATA 0x1c
#define XSCALER_CONTROL_BUS_BITS_SRC_COLS_DATA 32
#define XSCALER_CONTROL_BUS_ADDR_DST_COLS_DATA 0x24
#define XSCALER_CONTROL_BUS_BITS_DST_COLS_DATA 32
#define XSCALER_CONTROL_BUS_ADDR_DST_ROWS_DATA 0x2c
#define XSCALER_CONTROL_BUS_BITS_DST_ROWS_DATA 32

