// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xvideo_awb.h"

extern XVideo_awb_Config XVideo_awb_ConfigTable[];

XVideo_awb_Config *XVideo_awb_LookupConfig(u16 DeviceId) {
	XVideo_awb_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XVIDEO_AWB_NUM_INSTANCES; Index++) {
		if (XVideo_awb_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XVideo_awb_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XVideo_awb_Initialize(XVideo_awb *InstancePtr, u16 DeviceId) {
	XVideo_awb_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XVideo_awb_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XVideo_awb_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

