// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.4
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XVIDEO_AWB_H
#define XVIDEO_AWB_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xvideo_awb_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XVideo_awb_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XVideo_awb;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XVideo_awb_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XVideo_awb_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XVideo_awb_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XVideo_awb_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XVideo_awb_Initialize(XVideo_awb *InstancePtr, u16 DeviceId);
XVideo_awb_Config* XVideo_awb_LookupConfig(u16 DeviceId);
int XVideo_awb_CfgInitialize(XVideo_awb *InstancePtr, XVideo_awb_Config *ConfigPtr);
#else
int XVideo_awb_Initialize(XVideo_awb *InstancePtr, const char* InstanceName);
int XVideo_awb_Release(XVideo_awb *InstancePtr);
#endif

void XVideo_awb_Start(XVideo_awb *InstancePtr);
u32 XVideo_awb_IsDone(XVideo_awb *InstancePtr);
u32 XVideo_awb_IsIdle(XVideo_awb *InstancePtr);
u32 XVideo_awb_IsReady(XVideo_awb *InstancePtr);
void XVideo_awb_EnableAutoRestart(XVideo_awb *InstancePtr);
void XVideo_awb_DisableAutoRestart(XVideo_awb *InstancePtr);

void XVideo_awb_Set_src_rows(XVideo_awb *InstancePtr, u32 Data);
u32 XVideo_awb_Get_src_rows(XVideo_awb *InstancePtr);
void XVideo_awb_Set_src_cols(XVideo_awb *InstancePtr, u32 Data);
u32 XVideo_awb_Get_src_cols(XVideo_awb *InstancePtr);

void XVideo_awb_InterruptGlobalEnable(XVideo_awb *InstancePtr);
void XVideo_awb_InterruptGlobalDisable(XVideo_awb *InstancePtr);
void XVideo_awb_InterruptEnable(XVideo_awb *InstancePtr, u32 Mask);
void XVideo_awb_InterruptDisable(XVideo_awb *InstancePtr, u32 Mask);
void XVideo_awb_InterruptClear(XVideo_awb *InstancePtr, u32 Mask);
u32 XVideo_awb_InterruptGetEnabled(XVideo_awb *InstancePtr);
u32 XVideo_awb_InterruptGetStatus(XVideo_awb *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
